### ISSUE TITLE
ansible: CookieJar / LWPCookieJar class incompatibily while using the uri module.

### ISSUE THREAD

**Issue by kmARC** [dw/mitogen#113]
## Environment:
```shell
$ ansible --version
ansible 2.4.3.0
  config file = /builds/project-0/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12+ (default, Sep 17 2016, 12:08:02) [GCC 6.2.0 20160914]
$ uname -a
Linux runner--project-0-concurrent-0 4.15.1-041501-generic #201802031831 SMP Sat Feb 3 18:32:13 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
**OS:** Ubuntu 16:10 (Docker image)

## Task:

```yaml
- name: Get auth token
  uri:
    url: "https://keycloak.example.com/auth/realms/master/protocol/openid-connect/token"
    method: POST
    body: "client_id=admin-cli&username=admin&\
           password={{ keycloak_admin_password }}&grant_type=password"
    return_content: true
    validate_certs: false
  register: r_token
  no_log: false
  run_once: true
  delegate_to: localhost
```

## Example failure
```pytb
TASK [Get auth token] **********************************************************
task path: /builds/project-0/setup/client.yml:4
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 130, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 528, in _execute
    result = self._handler.run(task_vars=variables)
  File "/tmp/mitogen-master/ansible_mitogen/mixins.py", line 121, in run
    return super(ActionModuleMixin, self).run(tmp, task_vars)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/normal.py", line 45, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=wrap_async))
  File "/tmp/mitogen-master/ansible_mitogen/mixins.py", line 279, in _execute_module
    env=cast(env),
  File "/tmp/mitogen-master/ansible_mitogen/mixins.py", line 130, in call
    return self._connection.call(func, *args, **kwargs)
  File "/tmp/mitogen-master/ansible_mitogen/connection.py", line 231, in call
    return self.call_async(func, *args, **kwargs).get().unpickle()
  File "/tmp/mitogen-master/mitogen/core.py", line 314, in unpickle
    raise obj
CallError: exceptions.TypeError: unbound method __init__() must be called with CookieJar instance as first argument (got LWPCookieJar instance instead)
  File "<stdin>", line 1368, in _dispatch_calls
  File "<stdin>", line 1363, in _dispatch_one
  File "master:/tmp/mitogen-master/ansible_mitogen/helpers.py", line 128, in run_module
    mod.main()
  File "/usr/local/lib/python2.7/dist-packages/ansible/modules/net_tools/basics/uri.py", line 439, in main
    dict_headers, socket_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ansible/modules/net_tools/basics/uri.py", line 352, in uri
    method=method, timeout=socket_timeout)
  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/urls.py", line 1040, in fetch_url
    cookies = cookiejar.LWPCookieJar()
  File "/usr/lib/python2.7/cookielib.py", line 1758, in __init__
    CookieJar.__init__(self, policy)
```

**Comment by dw** [comment]
Which OS and ansible --version? Thanks

**Comment by dw** [comment]
Looks like some trickery involving six.py in module_utils/urls.py. Thanks for the report, will look at this tomorrow

**Comment by kmARC** [comment]
I just updated the original report. Thanks!

**Comment by mlaurense** [comment]
I can confirm the same issue when using apt_key:

`fatal: [production999.local]: FAILED! => {"changed": false, "msg": "error getting key id from url: https://deb.goaccess.io/gnugpg.key", "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/ansible/modules/packaging/os/apt_key.py\", line 205, in download_key\n    rsp, info = fetch_url(module, url)\n  File \"/usr/lib/python2.7/dist-packages/ansible/module_utils/urls.py\", line 1040, in fetch_url\n    cookies = cookiejar.LWPCookieJar()\n  File \"/usr/lib/python2.7/cookielib.py\", line 1758, in __init__\n    CookieJar.__init__(self, policy)\nTypeError: unbound method __init__() must be called with CookieJar instance as first argument (got LWPCookieJar instance instead)\n"}`

This appears when running ansible 2.4.3.0 / python 2.7.10 on OSX to a Ubuntu 16.04 machine.

**Comment by dw** [comment]
Thanks for letting me know! Will treat this with priority, it's a bug
affecting a helper module, so many more modules are likely impacted.

**Comment by dw** [comment]
What a fantastic catch! Thanks for reporting this, it was a huge bug that's gone unnoticed for a very long time :)
