### ISSUE TITLE
mitogen crashed with "error: unpack requires a string argument of length 12"

### ISSUE THREAD

**Issue by sirtux** [dw/mitogen#131]
Hi,

trying the lastest mitogen is crashing with "error: unpack requires a string argument of length 12" while running an apt task - the traceback is: 

```
TASK [jmetex : install jmetex] *******************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /Users/tom/repo/infrastructure/ansible/roles/jmetex/tasks/main.yml:6
[pid 9967] 17:29:19 D mitogen: unix.connect(path='/var/folders/jd/tvrdj3v55_z5ql3mgb4jky1c0000gn/T/mitogen_unix_Dc8KhF')
[pid 9953] 17:29:19 D mitogen: register(Context(9, None), mitogen.core.Stream('unix_client.9967'))
[pid 9967] 17:29:19 D mitogen: unix.connect(): local ID is 9, remote is 0
[pid 9967] 17:29:19 D mitogen: register(Context(0, None), mitogen.core.Stream('unix_listener.9953'))
[pid 9967] 17:29:19 D mitogen: Context(0, None).send_async(Message(None, 9, 9, 500, 1000, '\x80\x02}q\x01(U\x08usernameq\x02X\t\x00\x00\x00teichhornq\x03U\x0fcheck_host_key'..298))
[pid 9953] 17:29:19 D mitogen: put() done. woken? True
[pid 9967] 17:29:19 D mitogen: put() done. woken? True
[pid 9967] 17:29:19 D mitogen: Context(0, None).send_async(Message(None, 9, 9, 500, 1001, '\x80\x02}q\x01(U\x08usernameq\x02X\x04\x00\x00\x00rootq\x03U\x03viaq\x04cmitogen.core\n'..224))
[pid 9953] 17:29:19 D mitogen: put() done. woken? True
[pid 9967] 17:29:19 D mitogen: put() done. woken? True
[pid 9967] 17:29:19 D mitogen: Context(5, u'ssh.10.90.4.46.sudo.root').call_async(<function run_module at 0x10a470140>, *('ansible.modules.packaging.os.apt',), **{'args': {'_ansible_version': '2.4.3.0', '_ansible_selinux_special_fs': ['fuse', 'nfs', 'vboxsf', 'ramfs', '9p'], u'name': u'jmetex', '_ansible_module_name': u'apt', '_ansible_syslog_facility': u'LOG_USER', '_ansible_verbosity': 3, '_ansible_socket': None, '_ansible_diff': False, '_ansible_debug': False, '_ansible_shell_executable': u'/bin/sh', '_ansible_check_mode': False, '_ansible_no_log': False}, 'env': {}})
[pid 9967] 17:29:19 D mitogen: Context(5, u'ssh.10.90.4.46.sudo.root').send_async(Message(None, 9, 9, 101, 1002, '\x80\x02(U\x17ansible_mitogen.helpersq\x01NU\nrun_moduleq\x02U ans'..486))
[pid 9968] 17:29:19 D mitogen: unix.connect(path='/var/folders/jd/tvrdj3v55_z5ql3mgb4jky1c0000gn/T/mitogen_unix_Dc8KhF')
[pid 9953] 17:29:19 E mitogen: <mitogen.unix.Listener object at 0x10a47e3d0> crashed
Traceback (most recent call last):
  File "/Users/tom/repo/mitogen/mitogen/core.py", line 1185, in _call
    func(self)
  File "/Users/tom/repo/mitogen/mitogen/unix.py", line 81, in on_receive
    pid, = struct.unpack('>L', sock.recv(4))
error: [Errno 35] Resource temporarily unavailable
[pid 9953] 17:29:19 D mitogen: <mitogen.unix.Listener object at 0x10a47e3d0>.on_disconnect()
[pid 9968] 17:29:19 D ansible_mitogen.connection: Call run_module('ansible.modules.packaging.os.apt',) took 7 ms
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/2.4.3.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 130, in run
    res = self._execute()
  File "/usr/local/Cellar/ansible/2.4.3.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 528, in _execute
    result = self._handler.run(task_vars=variables)
  File "/Users/tom/repo/mitogen/ansible_mitogen/mixins.py", line 128, in run
    return super(ActionModuleMixin, self).run(tmp, task_vars)
  File "/usr/local/Cellar/ansible/2.4.3.0/libexec/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 45, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=wrap_async))
  File "/Users/tom/repo/mitogen/ansible_mitogen/mixins.py", line 308, in _execute_module
    env=cast(env),
  File "/Users/tom/repo/mitogen/ansible_mitogen/mixins.py", line 137, in call
    return self._connection.call(func, *args, **kwargs)
  File "/Users/tom/repo/mitogen/ansible_mitogen/connection.py", line 238, in call
    return self.call_async(func, *args, **kwargs).get().unpickle()
  File "/Users/tom/repo/mitogen/ansible_mitogen/connection.py", line 224, in call_async
    self._connect()
  File "/Users/tom/repo/mitogen/ansible_mitogen/connection.py", line 192, in _connect
    self.router, self.parent = mitogen.unix.connect(path)
  File "/Users/tom/repo/mitogen/mitogen/unix.py", line 100, in connect
    mitogen.context_id, remote_id, pid = struct.unpack('>LLL', sock.recv(12))
error: unpack requires a string argument of length 12

fatal: [DE-IX-001-02-02-05-4]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

Ansible and python versions:

```
ansible 2.4.3.0
  config file = /Users/tom/.ansible.cfg
  configured module search path = [u'/Users/tom/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.3.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

The relevant playbook part is this:

```
- name: install jmetex
  apt:
    name: jmetex
```

If you need further outputs please ask!
You're work is awesome!

Thanks,
Tom

**Comment by dw** [comment]
Hi Tom! Thanks for the report,  I'm mobile just now but will check when i
get home. Can you let me know:

- how many cpus?
- what ansible version and host os

**Comment by dw** [comment]
Still not home,  but i think i see the problem. What version of OS X?
Somehow a blocking mode socket is returning EAGAIN. Makes no sense :)

**Comment by sirtux** [comment]
This is MacOS 10.13.3 (17D102), with ansible 2.4.3.0, and 4 cores.

**Comment by dw** [comment]
This might be another manifestation of issue #123. Looking at this today.

Does this crash for you reliably, and does it always crash in the same spot?  I'm running on a 2 core / 4 thread 10.12  MacBook and have never experienced this. But there is a probably related bug (#123) where a 16 vCPU box exposes some synchronization issue.  I may attack that bug first to see if it has the same root cause as this one, as I am able to reproduce that bug.

**Comment by dw** [comment]
FWIW these ordering and synchronization issues are the hardest ones to find and diagnose, so please allow me a little time in figuring this one out :)

**Comment by sirtux** [comment]
Hi, yes this always crashed at the same spot. No pressure, this is not like a burning issue, I can run ansible fine without mitogen ,)

**Comment by rouge8** [comment]
I get this crash at different tasks when re-running. OS X 10.11.6 host, MBP 2 cores / 4 threads, tried with 1, 2, 3, and 4 hosts.

**Comment by dw** [comment]
Head swirling in other issues today, sorry for the delay. Can you confirm, are you using the Apple-supplied Python build or e.g. one from MacPorts?

**Comment by rouge8** [comment]
Mine is Homebrew:

```
ansible 2.4.3.0
  config file = /Users/andy/gr/myproject/ansible.cfg
  configured module search path = [u'/Users/andy/gr/myproject/ansible/library', u'/Users/andy/gr/myproject/ansible/library/vendor']
  ansible python module location = /Users/andy/gr/myproject/.tox/deploy/lib/python2.7/site-packages/ansible
  executable location = .tox/deploy/bin/ansible
  python version = 2.7.14 (default, Mar  1 2018, 19:23:40) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

**Comment by dw** [comment]
@rouge8 thanks! Can you confirm, does the issue present on e.g. run_hostname_100_times.yml in the examples/playbook/ directory against localhost and/or your real target machine. And if not, does examples/playbook/issue_131.yml tickle it?

**Comment by dw** [comment]
@rouge8 Can you possibly also include the output of ``ansible-config dump --only-changed`` from your project directory :) Thanks! Will try and have this one nailed tomorrow

**Comment by rouge8** [comment]
### Config:

```
ANSIBLE_FORCE_COLOR(/Users/andy/gr/myproject/ansible.cfg) = True
ANSIBLE_PIPELINING(/Users/andy/gr/myproject/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/andy/gr/myproject/ansible.cfg) = -F ansible/ssh_config -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_CALLBACK_WHITELIST(/Users/andy/gr/myproject/ansible.cfg) = ['timer']
DEFAULT_FORKS(/Users/andy/gr/myproject/ansible.cfg) = 50
DEFAULT_GATHERING(/Users/andy/gr/myproject/ansible.cfg) = smart
DEFAULT_GATHER_SUBSET(/Users/andy/gr/myproject/ansible.cfg) = all,!ohai,!facter
DEFAULT_HOST_LIST(/Users/andy/gr/myproject/ansible.cfg) = [u'/Users/andy/gr/myproject/ansible/inventory_from_ssh_config.py']
DEFAULT_MODULE_PATH(/Users/andy/gr/myproject/ansible.cfg) = [u'/Users/andy/gr/myproject/ansible/library', u'/Users/andy/gr/myproject/ansible/library/vendor']
DEFAULT_ROLES_PATH(/Users/andy/gr/myproject/ansible.cfg) = [u'/Users/andy/gr/myproject/ansible/roles', u'/Users/andy/gr/myproject/ansible/shared_roles']
DEFAULT_STRATEGY(/Users/andy/gr/myproject/ansible.cfg) = mitogen
DEFAULT_STRATEGY_PLUGIN_PATH(/Users/andy/gr/myproject/ansible.cfg) = [u'/Users/andy/forks/mitogen/ansible_mitogen/plugins/strategy']
```

### `run_hostname_100_times.yml`

All runs are on 4 hosts.

- Worked the first time I ran it
- Crashed the second, immediately after
- Waited a couple minutes (longer than the `ControlPersist=60s`), reran. No crash
- Reran several times immediately. No crash. 😕 

### `issue_131.yml`

All runs on the same 4 hosts.

Ran immediately after `run_hostname_100_times.yml`:

```
PLAY [all] ************************************************************************************************************

TASK [command] ********************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: error: unpack requires a string argument of length 12
fatal: [env1-stage-bastion]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
changed: [env2-stage-bastion]
changed: [env2-prod-bastion]
changed: [env2-demo-bastion]

TASK [command] ********************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: error: [Errno 61] Connection refused
fatal: [env2-stage-bastion]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: error: [Errno 61] Connection refused
fatal: [env2-prod-bastion]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: error: [Errno 61] Connection refused
fatal: [env2-demo-bastion]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
	to retry, use: --limit @/Users/andy/forks/mitogen/examples/playbook/issue_131.retry

PLAY RECAP ************************************************************************************************************
env2-demo-bastion        : ok=1    changed=1    unreachable=0    failed=1
env2-prod-bastion        : ok=1    changed=1    unreachable=0    failed=1
env2-stage-bastion       : ok=1    changed=1    unreachable=0    failed=1
env1-stage-bastion        : ok=0    changed=0    unreachable=0    failed=1
```

Ran a second time, same results. Ran a _third_ time, all hosts succeeded for the first command, `env2-demo-bastion` failed the second, `env2-prod-bastion` and `env2-stage-bastion` succeeded, and `env1-stage-bastion` appears to have hung.

**Comment by dw** [comment]
You got me excited when I saw ANSIBLE_FORKS=50, because I never test with that, only to have hopes dashed on seeing my playbook of a single step (run_hostname..) also crashing :P~ 

So it looks a hell of a lot like a threading issue in the top-level process itself, not in any worker. It simply shouldn't be possible for ECONNREFUSED to happen during a run, so this has already been very useful.

Thanks again so much for your help!

**Comment by dw** [comment]
Finally managed to reproduce this locally. WIP

**Comment by dw** [comment]
Sorry for the delay, this was actually a really simple bug and I should have spotted it much earlier.

As for why you saw it and I did not, either that is due to a large forks setting, or because your machines are sufficiently busy to starve the new worker process of the chance to write its identity to the socket before the master attempted to read it.

Can you please confirm the issue is now gone on latest master.

**Comment by sirtux** [comment]
Hi, I can confirm this error is gone

**Comment by rouge8** [comment]
Same, no longer crashing for me. 🎉 

My actual playbook is slower than previous non-crashing runs though. I'll try and debug and/or simplify that and open a separate issue when I figure it out. 😕

**Comment by dw** [comment]
That does not sound helpful! Please keep spamming me these tickets, and always be sure to mention the modules involved. Note if you were timing using the ansible.cfg in the examples directory, it now has forks=50 by default. I have zero clue how much perf impact that will have (but I guess we're going to find out over the coming days :))

**Comment by rouge8** [comment]
It might also be something going with the network -- that same playbook is also slower today without Mitogen than it was yesterday 🙃  I'll open issue(s) if I figure out more!

**Comment by dw** [comment]
I've got some vague thoughts around a built-in profiling function that would capture this kind of stuff "for free". Something like that popular callback plug-in, but on steroids, since we have an obscene level of visibility into the remote process (e.g. per task getrusage()) and have smart code at every network endpoint (e.g. latency or bandwidth monitoring via adding message timestamps, etc)
