### ISSUE TITLE
core: ridiculous use of defer() in stack trace due to LogForwarder

### ISSUE THREAD

**Issue by dw** [dw/mitogen#166]
At least some of the defer() calls should be removed from this trace. I had an old stash to do it, but it's far too out of date now.

````python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1352, in _broker_main
  File "<stdin>", line 719, in on_disconnect
  File "<stdin>", line 161, in fire
  File "<stdin>", line 1386, in _on_parent_disconnect
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1155, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "<stdin>", line 655, in emit
  File "<stdin>", line 876, in send
  File "<stdin>", line 1231, in route
  File "<stdin>", line 1255, in defer
  File "<stdin>", line 1228, in _async_route
  File "<stdin>", line 838, in send
  File "<stdin>", line 1255, in defer
  File "<stdin>", line 833, in _send
  File "<stdin>", line 1281, in start_transmit
AssertionError
````

**Comment by dw** [comment]
Fixed as of 8676c40674fbbb4372f89b0b9804af0a4140a2a0
