### ISSUE TITLE
mitop: regression during CTRL+C

### ISSUE THREAD

**Issue by dw** [dw/mitogen#176]
mitop.py throws an exception at exit:

````
12:36:18 E mitogen: _broker_main() crashed
Traceback (most recent call last):
  File "/Users/dmw/src/mitogen/mitogen/core.py", line 1442, in _broker_main
    fire(self, 'shutdown')
  File "/Users/dmw/src/mitogen/mitogen/core.py", line 171, in fire
    return [func(*args, **kwargs) for func in signals.get(name, ())]
  File "/Users/dmw/src/mitogen/mitogen/core.py", line 1248, in on_broker_shutdown
    self._cleanup_handlers()
  File "/Users/dmw/src/mitogen/mitogen/core.py", line 1253, in _cleanup_handlers
    func(_DEAD)
  File "/Users/dmw/src/mitogen/mitogen/core.py", line 439, in _on_receive
    self.notify(self)
  File "/Users/dmw/src/mitogen/mitogen/master.py", line 202, in _put
    self._latch.put(value)
  File "/Users/dmw/src/mitogen/mitogen/core.py", line 1064, in put
    self._wake(sock)
  File "/Users/dmw/src/mitogen/mitogen/core.py", line 1070, in _wake
    os.write(sock.fileno(), '\x7f')
OSError: [Errno 32] Broken pipe
````

**Comment by dw** [comment]
Fixed a million years ago
