### ISSUE TITLE
Unsure how to call user-defined functions in Mitogen context

### ISSUE THREAD

**Issue by AndrewC-B** [dw/mitogen#252]
**What I'm trying to do**
Run a user defined function in a Mitogen context (via SSH).

**What I've tried so far**
You can see my code below. I can successfully call a built-in function like `time.time` (see my comment below). But I cannot substitute this for a user-defined function like `mitogen_task`, as shown below.

**Background**
I've just started poking around with Mitogen and I'm making things even harder for myself by trying to use the Python 3 branch. I completely understand that this is an unreleased branch of pre-release software, so no worries if it's not worth looking into this (in which case please feel free to close the issue). But if anyone is able to shed any light on the problem I'd be grateful.

**Code**

```
def my_function():
    broker = mitogen.master.Broker()
         router = mitogen.master.Router(broker)
         host = router.ssh(
         hostname='10.0.0.1',
         username='vagrant',
         identity_file='/home/vagrant/.ssh/id_rsa'
    )
     try:
          host.call(mitogen_task)
     finally:
          broker.shutdown()

def mitogen_task():
     print("Hello from remote!")

if __name__ == '__main__':
    # Call code which boots sshd on 10.0.0.1
    # After waiting for 10.0.0.1:22 to start responding:
    my_function()
```

**Output**

```
  DEBUG    mitogen                        mitogen.ssh.Stream('default').connect()
  DEBUG    mitogen                        hybrid_tty_create_child() pid=16934 stdio=26, tty=25, cmd: "ssh" "-l" "vagrant" "-o" "IdentitiesOnly yes" "-i" "/home/vagrant/.ssh/id_rsa" "-o" "Compression yes" "-o" "ServerAliveInterval 15" "-o" "ServerAliveCountMax 3" "-o" "StrictHostKeyChecking yes" "10.0.0.1" "python2.7" "-c" "'import codecs,os,sys;_=codecs.decode;exec(_(_(\"eNpVkE1LxDAQhs/2V3ibhA1L0v0QCoWVIt57sAcV6UcqYWsS0q5Rf72zRHeT2zwzL++8MzVrSjOvrbKS0MwxH5EabxFG446EFtkN1sPJ5oQzwTm9cs1icjgVgfvJzJLUMbgYmhh8AKk/lTP6Ge7rxycOr+X8jc0v2Z+Wtptk0CBOJB2wFFdAPtRi3qUunDHLYWw7p/pdIfb7fEOBZmjjnVokEQweKv6iAVf3ZsC7aVaVb+R8+WCs1HgvuA7o2sl2IEJs+JYy+FEWXfxoy6uwYeA7OH8D+3/2Fc2aROQvouYigm2+y+/iDKsqmITfBO1/nUYXSfRf0kSOlg==\".encode(),\"base64\"),\"zip\"))'"
  DEBUG    mitogen                        mitogen.ssh.Stream('local.16934').connect(): child process stdin/stdout=26
  DEBUG    mitogen                        mitogen.ssh.Stream('local.16934'): received b'EC0\n'
  DEBUG    mitogen                        mitogen.ssh.Stream('local.16934')._ec0_received()
  DEBUG    mitogen                        register(Context(1, 'ssh.10.0.0.1'), mitogen.ssh.Stream('ssh.10.0.0.1'))
  DEBUG    mitogen                        Context(1, 'ssh.10.0.0.1').call_async(<function mitogen_task at 0x7f94f6377f28>, *(), **{})
  DEBUG    mitogen                        Context(1, 'ssh.10.0.0.1').send_async(Message(1, 0, 0, 101, 1000, b'\x80\x02(X\x08\x00\x00\x00__main__q\x00NX\x0c\x00\x00\x00mitogen_taskq\x01)}q\x02tq\x03.'..46))
  DEBUG    mitogen                        ModuleResponder(Router(Broker(0x7f94f19eb518)))._on_get_module(b'__main__')
  DEBUG    mitogen                        While importing '__main__'
Traceback (most recent call last):
  File "/usr/lib/python3.5/pkgutil.py", line 485, in find_loader
    spec = importlib.util.find_spec(fullname)
  File "/usr/lib/python3.5/importlib/util.py", line 102, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: __main__.__spec__ is None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mitogen-0.0.2-py3.5.egg/mitogen/master.py", line 662, in _on_get_module
    tup = self._build_tuple(fullname)
  File "/usr/local/lib/python3.5/dist-packages/mitogen-0.0.2-py3.5.egg/mitogen/master.py", line 614, in _build_tuple
    path, source, is_pkg = self._finder.get_module_source(fullname)
  File "/usr/local/lib/python3.5/dist-packages/mitogen-0.0.2-py3.5.egg/mitogen/master.py", line 467, in get_module_source
    tup = method(self, fullname)
  File "/usr/local/lib/python3.5/dist-packages/mitogen-0.0.2-py3.5.egg/mitogen/master.py", line 398, in _get_module_via_pkgutil
    loader = pkgutil.find_loader(fullname)
  File "/usr/lib/python3.5/pkgutil.py", line 491, in find_loader
    raise ImportError(msg.format(fullname, type(ex), ex)) from ex
ImportError: Error while finding loader for '__main__' (<class 'ValueError'>: __main__.__spec__ is None)
  DEBUG    mitogen                        Broker(0x7f94f19eb518).shutdown()
  ERROR    experiments.utils.util         Error while running experiment: exceptions.ImportError: Master does not have '__main__'
  File "<stdin>", line 1760, in _dispatch_calls
  File "<stdin>", line 1747, in _dispatch_one
  File "<stdin>", line 719, in load_module

  DEBUG    mitogen                        Waker(Broker(0x7f94f19eb518) rfd=22, wfd=24).on_shutdown()
  DEBUG    mitogen                        Waker(Broker(0x7f94f19eb518) rfd=22, wfd=24).on_disconnect()
  DEBUG    mitogen                        mitogen.ssh.Stream('ssh.10.0.0.1') closing CALL_FUNCTION channel
  DEBUG    mitogen.ctx.ssh.10.0.0.1       mitogen: Waker(Broker(0x7f2cb34f0150) rfd=3, wfd=4).on_disconnect()
  DEBUG    mitogen                        mitogen.parent.TtyLogStream(mitogen.ssh.Stream('ssh.10.0.0.1')).on_disconnect()
  DEBUG    mitogen                        mitogen.ssh.Stream('ssh.10.0.0.1'): child process exit status was 65280
  DEBUG    mitogen                        mitogen.ssh.Stream('ssh.10.0.0.1').on_disconnect()
  DEBUG    mitogen                        mitogen.ssh.Stream('ssh.10.0.0.1') is gone; propagating DEL_ROUTE for {1}
  DEBUG    mitogen                        Router(Broker(0x7f94f19eb518)).del_route(1)

…

  File "/path/to/my/script.py", line X, in my_function
    host.call(mitogen_task)
  File "/usr/local/lib/python3.5/dist-packages/mitogen-0.0.2-py3.5.egg/mitogen/parent.py", line 827, in call
    return receiver.get().unpickle(throw_dead=False)
  File "/usr/local/lib/python3.5/dist-packages/mitogen-0.0.2-py3.5.egg/mitogen/core.py", line 417, in unpickle
    raise obj
mitogen.core.CallError: exceptions.ImportError: Master does not have '__main__'
  File "<stdin>", line 1760, in _dispatch_calls
  File "<stdin>", line 1747, in _dispatch_one
  File "<stdin>", line 719, in load_module
```

**Comment by AndrewC-B** [comment]
I've figured out enough to realise that the relevant documentation is [here](https://mitogen.readthedocs.io/en/latest/getting_started.html#running-user-functions) but thus far I haven't been able to figure out how I need to change my code so that it works correctly. In the code below, if I change `host.call(mitogen_task)` to `host.call(time.time)` everything works. 

Clearly I'm not understanding something about how Mitogen works. I'll keep reading the documentation and update this thread if I make any progress.

**Comment by AndrewC-B** [comment]
I also saw some errors when I installed Mitogen. They seem unrelated, but I'll include them here for completeness.

```
$ sudo python3 setup.py install
running install
Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.5/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating mitogen.egg-info
writing top-level names to mitogen.egg-info/top_level.txt
writing mitogen.egg-info/PKG-INFO
writing dependency_links to mitogen.egg-info/dependency_links.txt
writing manifest file 'mitogen.egg-info/SOURCES.txt'
reading manifest file 'mitogen.egg-info/SOURCES.txt'
writing manifest file 'mitogen.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/mitogen
copying mitogen/setns.py -> build/lib/mitogen
copying mitogen/jail.py -> build/lib/mitogen
copying mitogen/parent.py -> build/lib/mitogen
copying mitogen/unix.py -> build/lib/mitogen
copying mitogen/__init__.py -> build/lib/mitogen
copying mitogen/debug.py -> build/lib/mitogen
copying mitogen/service.py -> build/lib/mitogen
copying mitogen/sudo.py -> build/lib/mitogen
copying mitogen/fakessh.py -> build/lib/mitogen
copying mitogen/ssh.py -> build/lib/mitogen
copying mitogen/su.py -> build/lib/mitogen
copying mitogen/docker.py -> build/lib/mitogen
copying mitogen/utils.py -> build/lib/mitogen
copying mitogen/lxc.py -> build/lib/mitogen
copying mitogen/master.py -> build/lib/mitogen
copying mitogen/fork.py -> build/lib/mitogen
copying mitogen/core.py -> build/lib/mitogen
  File "build/bdist.linux-x86_64/egg/ansible_mitogen/services.py", line 344
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying mitogen.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mitogen.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating /usr/local/lib/python3.5/dist-packages/mitogen-0.0.2-py3.5.egg
Extracting mitogen-0.0.2-py3.5.egg to /usr/local/lib/python3.5/dist-packages
  File "/usr/local/lib/python3.5/dist-packages/mitogen-0.0.2-py3.5.egg/mitogen/setns.py", line 154
    except Exception, e:
                    ^
    os.chmod(self.path, 0600)
    print "%d,%d-%d,%d:\t%s\t%s" % \
    except IOError, msg:
                  ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.5/dist-packages/mitogen-0.0.2-py3.5.egg/ansible_mitogen/runner.py", line 303
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.5/dist-packages/mitogen-0.0.2-py3.5.egg/ansible_mitogen/module_finder.py", line 137
    print '%s: %s' % (name, imported and (str(name) == imported.fullname()))
                 ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.5/dist-packages/mitogen-0.0.2-py3.5.egg/ansible_mitogen/target.py", line 208
    except OSError, e:
                  ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.5/dist-packages/mitogen-0.0.2-py3.5.egg/ansible_mitogen/process.py", line 173
    except OSError, e:
                  ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.5/dist-packages/mitogen-0.0.2-py3.5.egg/ansible_mitogen/services.py", line 344
    raise e1, e2, e3
            ^
SyntaxError: invalid syntax

Adding mitogen 0.0.2 to easy-install.pth file

Installed /usr/local/lib/python3.5/dist-packages/mitogen-0.0.2-py3.5.egg
Processing dependencies for mitogen==0.0.2
Finished processing dependencies for mitogen==0.0.2
```

**Comment by dw** [comment]
Hi there,

Python 3 is not yet supported. There is a branch for it, but it's not ready for prime time. That explains the syntax errors - you must install with Python 2 for the coming weeks.

**Comment by dw** [comment]
Oh whoa, you're on Python 3 branch :) Yes, please totally ignore it for now. It's seriously a construction site -- there is no point in even trying yet.

**Comment by dw** [comment]
I'm keeping this bug open because I haven't seen this stack trace before! :)  Python 3 support is really that fresh.

**Comment by AndrewC-B** [comment]
Haha, OK. Fair enough. I came here from your [comment](https://github.com/fabric/fabric/issues/237#issuecomment-387147613). Technically it has been more than two weeks 😜

**Comment by dw** [comment]
Soon I promise :)  Currently battling scaling issues with Ansible, so a little distracted from pushing the core library forward. Python 3 really isn't that hard a target to hit, just requires time, and as you've encountered, apparently some tweaks in the module importer

**Comment by AndrewC-B** [comment]
OK, good to hear! Thanks!

**Comment by dw** [comment]
Hi @AndrewC-B, just to let you know the python3 branch is at long last finished and merged to master. I should have a stable release on PyPI sometime tomorrow evening. Horay!

**Comment by AndrewC-B** [comment]
Thanks @dw! I came up with my own solution in the meantime, but that’s great to hear. I’ll look for an excuse to check it out some time soon :)
