### ISSUE TITLE
core: broken pipe while writing to waker

### ISSUE THREAD

**Issue by dw** [dw/mitogen#286]
````
00:14:29 D mitogen.ctx.fork.5784: mitogen: _dispatch_calls: Caller is not authorized to invoke 'privileged_op' of service 'service_test.MyService'
00:14:29 D mitogen: Broker(0x7f44cb0c4950).shutdown()
00:14:29 D mitogen: Waker(Broker(0x7f44cb0c4950) rfd=66, wfd=68).on_shutdown()
00:14:29 D mitogen: Waker(Broker(0x7f44cb0c4950) rfd=66, wfd=68).on_disconnect()
00:14:29 D mitogen: mitogen.fork.Stream('fork.5765') closing CALL_FUNCTION channel
00:14:29 D mitogen: mitogen.fork.Stream('fork.5784') closing CALL_FUNCTION channel
00:14:29 D mitogen.ctx.fork.5784: mitogen: _on_shutdown_msg(Message(2, 0, 0, 106, 0, ''..0))
00:14:29 D mitogen.ctx.fork.5765: mitogen: _on_shutdown_msg(Message(1, 0, 0, 106, 0, ''..0))
00:14:29 D mitogen: mitogen.fork.Stream('fork.5765'): child process still alive, sending SIGTERM
00:14:29 D mitogen: mitogen.fork.Stream('fork.5765').on_disconnect()
00:14:29 D mitogen: mitogen.fork.Stream('fork.5765') is gone; propagating DEL_ROUTE for set([1])
00:14:29 D mitogen: Router(Broker(0x7f44cb0c4950)).del_route(1)
00:14:29 D mitogen: mitogen.fork.Stream('fork.5784'): child process exit status was 15
00:14:29 D mitogen: mitogen.fork.Stream('fork.5784').on_disconnect()
00:14:29 D mitogen: mitogen.fork.Stream('fork.5784') is gone; propagating DEL_ROUTE for set([2])
00:14:29 D mitogen: Router(Broker(0x7f44cb0c4950)).del_route(2)
ok
test_sibling_unprivileged_ok (service_test.PermissionTest) ... 00:14:29 D mitogen: mitogen.fork.Stream('default').connect()
00:14:29 D mitogen: mitogen.fork.Stream('fork.5787').connect(): child process stdin/stdout=118
00:14:29 D mitogen: register(Context(1, 'fork.5787'), mitogen.fork.Stream('fork.5787'))
00:14:29 D mitogen: Context(1, 'fork.5787').call_service_async(<class 'service_test.MyService'>, 'get_id', {})
00:14:29 D mitogen: Context(1, 'fork.5787').send_async(Message(1, 0, 0, 110, 1000, '\x80\x02U\x16service_test.MyServiceq\x01U\x06get_idq\x02}q\x03\x87q\x04.'..45))
00:14:29 E mitogen.ctx.fork.5787: mitogen: Router(Broker(0x7f44cb05ee50)): no route for Message(0, 1, 1, 102, None, "mitogen\x0010\x00register(Context(0, 'master'), mitogen."..72), my ID is 1
00:14:29 D mitogen.ctx.fork.5787: mitogen: Connected to Context(0, 'master'); my ID is 1, PID is 5787
00:14:29 D mitogen.ctx.fork.5787: mitogen: Recovered sys.executable: '/home/travis/virtualenv/python2.7.14/bin/python'
00:14:29 D mitogen.ctx.fork.5787: mitogen: mitogen.service.Pool(0x7f44c8307cd0, size=16, th='Thread-13'): initialized
00:14:29 D mitogen: mitogen.fork.Stream('default').connect()
00:14:29 D mitogen: mitogen.fork.Stream('fork.5806').connect(): child process stdin/stdout=120
00:14:29 D mitogen: register(Context(2, 'fork.5806'), mitogen.fork.Stream('fork.5806'))
00:14:29 D mitogen: Context(2, 'fork.5806').call_async(<function call_service_in at 0x7f44cb0c9ed8>, *(Context(1, 'fork.5787'), 'service_test.MyService', 'unprivileged_op'), **{})
00:14:29 D mitogen: Context(2, 'fork.5806').send_async(Message(2, 0, 0, 101, 1001, '\x80\x02(U\x0cservice_testq\x01NU\x0fcall_service_inq\x02cmitogen.co'..147))
00:14:29 D mitogen.ctx.fork.5806: mitogen: register(Context(0, 'master'), mitogen.core.Stream('parent'))
00:14:29 D mitogen.ctx.fork.5806: mitogen: Connected to Context(0, 'master'); my ID is 2, PID is 5806
00:14:29 D mitogen.ctx.fork.5806: mitogen: Recovered sys.executable: '/home/travis/virtualenv/python2.7.14/bin/python'
00:14:29 D mitogen.ctx.fork.5806: mitogen: _dispatch_calls(('service_test', None, 'call_service_in', (Context(1, 'fork.5787'), 'service_test.MyService', 'unprivileged_op'), {}))
00:14:29 D mitogen.ctx.fork.5806: mitogen: Context(1, 'fork.5787').call_service_async('service_test.MyService', 'unprivileged_op', {})
00:14:29 D mitogen.ctx.fork.5806: mitogen: Context(1, 'fork.5787').send_async(Message(1, 2, 2, 110, 1000, '\x80\x02U\x16service_test.MyServiceq\x01U\x0funprivileged_opq\x02}q\x03'..54))
00:14:30 E mitogen.ctx.fork.5787: mitogen: Router(Broker(0x7f44cb05ee50))._invoke(Message(1, 2, 2, 110, 1000, '\x80\x02U\x16service_test.MyServiceq\x01U\x0funprivileged_opq\x02}q\x03'..54)): <bound method Receiver._on_receive of Receiver(Router(Broker(0x7f44cb05ee50)), 110)> crashed
Traceback (most recent call last):
  File "/home/travis/build/dw/mitogen/mitogen/core.py", line 1474, in _invoke
    fn(msg)
  File "/home/travis/build/dw/mitogen/mitogen/core.py", line 493, in _on_receive
    self.notify(self)
  File "/home/travis/build/dw/mitogen/mitogen/select.py", line 51, in _put
    self._latch.put(value)
  File "/home/travis/build/dw/mitogen/mitogen/core.py", line 1220, in put
    self._wake(sock)
  File "/home/travis/build/dw/mitogen/mitogen/core.py", line 1226, in _wake
    os.write(sock.fileno(), '\x7f')
OSError: [Errno 32] Broken pipe
````

**Comment by dw** [comment]
Likely a manifestation of #417 or #420, either way it hasn't manifested in 6+ months
