### ISSUE TITLE
ansible: 'module' object has no attribute 'linear' when first play doesn't use mitogen

### ISSUE THREAD

**Issue by manicminer** [dw/mitogen#294]
With a playbook where the first play uses the Ansible stock `linear` strategy, an error is thrown when encountering the first play where `mitogen_linear` is to be used.

# To reproduce

```yaml
---
- name: LINEAR
  hosts: localhost
  strategy: linear
  tasks:
    - debug:
        msg: Linear strategy here

- name: MITOGEN
  hosts: localhost
  strategy: mitogen_linear
  tasks:
    - debug:
        msg: Mitogen linear strategy here
```

# Traceback
```
PLAY [MITOGEN] ******************************************************************************************************************************************************************************************
ERROR! Unexpected Exception, this is probably a bug: 'module' object has no attribute 'linear'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 159, in run
    result = self._tqm.run(play=play)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 268, in run
    strategy = strategy_loader.get(new_play.strategy, self)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/loader.py", line 366, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/loader.py", line 345, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/home/tom/git/infrastructure/ansible/vendor/mitogen/ansible_mitogen/plugins/strategy/mitogen_linear.py", line 59, in <module>
    ansible.plugins.strategy.linear.StrategyModule):
AttributeError: 'module' object has no attribute 'linear'
```

**Comment by dw** [comment]
Thanks for the report! Which version are you running on?

Regardless it's probably common across versions - "ansible.plugins.strategy.*" is a magic namespace managed by Ansible's PluginLoader. The solution is probably to avoid direct import, but asking PluginLoader to do it for us.

Will look at this real soon -- trying to finish last niggles on python3 branch so it can finally be merged

**Comment by dw** [comment]
This is fixed on the latest master :) Thanks for reporting!

**Comment by manicminer** [comment]
Looks like the fix is in `stable` too. Amazing, thanks!
