### ISSUE TITLE
[ansible] /etc/environment modifications are not reflected in future tasks

### ISSUE THREAD

**Issue by dw** [dw/mitogen#338]
On Ubuntu Linux, /etc/environment is read in by pam_env, which ordinarily happens at the start of every (multiplexed) SSH connection, and once every time sudo is invoked, so applies to every "become: true" task.

Since we use persistent interpreters, changes to /etc/environment by a task are not reflecting in subsequent tasks, as no component is reloading it. This is identical to an older issue with /etc/resolv.conf, and the fix seems to be the same.

We could try to exactly mimic the circumstances regular Ansible will receive the /etc/environment reloading behaviour (e.g. not applying it when "become: false"), but it seems harmless to just always apply the fix, and much easier to document in this case too.

Note: solution must also consider ~/.pam_environment, which is also read by pam_env

File format is here: https://github.com/linux-pam/linux-pam/blob/master/modules/pam_env/pam_env.c#L207

**Comment by dw** [comment]
For the benefit of search, this manifests with a 'become: true' pip invocation as:

````
:stderr: Exception:
Traceback (most recent call last):
 File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
 status = self.run(options, args)
 File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
 wb.build(autobuilding=True)
 File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
 self.requirement_set.prepare_files(self.finder)
 File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
 ignore_dependencies=self.ignore_dependencies))
 File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 512, in _prepare_file
 finder, self.upgrade, require_hashes)
 File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 273, in populate_link
 self.link = finder.find_requirement(self, upgrade)
 File "/usr/lib/python2.7/dist-packages/pip/index.py", line 442, in find_requirement
 all_candidates = self.find_all_candidates(req.name)
 File "/usr/lib/python2.7/dist-packages/pip/index.py", line 400, in find_all_candidates
 for page in self._get_pages(url_locations, project_name):
 File "/usr/lib/python2.7/dist-packages/pip/index.py", line 545, in _get_pages
 page = self._get_page(location)
 File "/usr/lib/python2.7/dist-packages/pip/index.py", line 648, in _get_page
 return HTMLPage.get_page(link, session=self.session)
 File "/usr/lib/python2.7/dist-packages/pip/index.py", line 757, in get_page
 "Cache-Control": "max-age=600",
 File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 480, in get
 return self.request('GET', url, **kwargs)
 File "/usr/lib/python2.7/dist-packages/pip/download.py", line 378, in request
 return super(PipSession, self).request(method, url, *args, **kwargs)
 File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 468, in request
 resp = self.send(prep, **send_kwargs)
 File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 576, in send
 r = adapter.send(request, **kwargs)
 File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py", line 46, in send
 resp = super(CacheControlAdapter, self).send(request, **kw)
 File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/adapters.py", line 376, in send
 timeout=timeout
 File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 610, in urlopen
 _stacktrace=sys.exc_info()[2])
 File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 228, in increment
 total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
````

**Comment by dw** [comment]
This will make it into the next release. To be updated when a new release is made, subscribe to https://www.freelists.org/list/mitogen-announce

Thanks for reporting this!
