### ISSUE TITLE
ContextService shutdown failure raising KeyError during tests

### ISSUE THREAD

**Issue by dw** [dw/mitogen#360]
Log attached.

[hardcopy.0.weird-shutdown-bug.txt](https://github.com/dw/mitogen/files/2371541/hardcopy.0.weird-shutdown-bug.txt)

````
[pid 15886] 08:02:15.226548 D ansible_mitogen.services: ContextService().put(Context(5018, u'ssh.localhost:2202'))
[pid 22072] 08:02:15.227143 D mitogen: mitogen.core.Stream(u'unix_listener.15886').on_disconnect()
[pid 15886] 08:02:15.227583 D mitogen: mitogen.core.Stream(u'unix_client.22072').on_disconnect()
[pid 22072] 08:02:15.228129 D mitogen: Waker(Broker(0x7fb974fc2fd0) rfd=27, wfd=29).on_disconnect()
The full traceback is:
Traceback (most recent call last):
  File "/home/dmw/src/mitogen/.venv/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 138, in run
    res = self._execute()
  File "/home/dmw/src/mitogen/.venv/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 576, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/dmw/src/mitogen/ansible_mitogen/mixins.py", line 116, in run
    return super(ActionModuleMixin, self).run(tmp, task_vars)
  File "/home/dmw/src/mitogen/tests/ansible/lib/action/mitogen_shutdown_all.py", line 27, in run
    method_name='shutdown_all',
  File "/home/dmw/src/mitogen/mitogen/core.py", line 1248, in call_service
    return recv.get().unpickle()
  File "/home/dmw/src/mitogen/mitogen/core.py", line 595, in unpickle
    raise obj
CallError: exceptions.KeyError: u'Nonevialocalmethod/tmp/issue_152_interpreter.shpython_pathkwargs'
  File "/home/dmw/src/mitogen/mitogen/service.py", line 519, in _on_service_call
    return invoker.invoke(method_name, kwargs, msg)
  File "/home/dmw/src/mitogen/mitogen/service.py", line 253, in invoke
    response = self._invoke(method_name, kwargs, msg)
  File "/home/dmw/src/mitogen/mitogen/service.py", line 239, in _invoke
    ret = method(**kwargs)
  File "/home/dmw/src/mitogen/ansible_mitogen/services.py", line 235, in shutdown_all
    self._shutdown(context)
  File "/home/dmw/src/mitogen/ansible_mitogen/services.py", line 198, in _shutdown
    del self._response_by_key[key]
````

**Comment by dw** [comment]
Relevant code was also refactored for 0.2.4 to fix a few more KeyErrors, assuming this one is fixed.
