### ISSUE TITLE
random FileServer premature exit during tests.

### ISSUE THREAD

**Issue by dw** [dw/mitogen#364]
Only happens on Travis CI, repeated soaking on an equivalent VM fails to reveal it.

````

TASK [copy dest=/tmp/copy-large-inline-file.out, content={% for x in range(200000) %}y{% endfor %}
] ***
[0;31mERROR! [pid 6803] 20:19:21.703900 E mitogen.ctx.ssh.localhost:2201: mitogen: get_file(u'/tmp/tmp5j62F6'): receiver was closed early, controller is likely shutting down.[0m
[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was:     raise IOError('transfer of %r was interrupted.' % (in_path,))[0m
[0;31mfatal: /home/travis/build/dw/mitogen/tests/ansible/integration/action/copy.yml:44: [target-debian]: FAILED! => {[0m
[0;31m  exception: Traceback (most recent call last):[0m
[0;31m  exception:   File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/ansible/executor/task_executor.py", line 148, in run[0m
[0;31m  exception:     res = self._execute()[0m
[0;31m  exception:   File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/ansible/executor/task_executor.py", line 551, in _execute[0m
[0;31m  exception:     result = self._handler.run(task_vars=variables)[0m
[0;31m  exception:   File "/home/travis/build/dw/mitogen/ansible_mitogen/mixins.py", line 116, in run[0m
[0;31m  exception:     return super(ActionModuleMixin, self).run(tmp, task_vars)[0m
[0;31m  exception:   File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/ansible/plugins/action/copy.py", line 516, in run[0m
[0;31m  exception:     module_return = self._copy_file(source_full, source_rel, content, content_tempfile, dest, task_vars, tmp, delete_remote_tmp)[0m
[0;31m  exception:   File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/ansible/plugins/action/copy.py", line 273, in _copy_file[0m
[0;31m  exception:     remote_path = self._transfer_file(source_full, tmp_src)[0m
[0;31m  exception:   File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/ansible/plugins/action/__init__.py", line 310, in _transfer_file[0m
[0;31m  exception:     self._connection.put_file(local_path, remote_path)[0m
[0;31m  exception:   File "/home/travis/build/dw/mitogen/ansible_mitogen/connection.py", line 898, in put_file[0m
[0;31m  exception:     out_path=out_path[0m
[0;31m  exception:   File "/home/travis/build/dw/mitogen/ansible_mitogen/connection.py", line 429, in call[0m
[0;31m  exception:     return self._rethrow(recv)[0m
[0;31m  exception:   File "/home/travis/build/dw/mitogen/ansible_mitogen/connection.py", line 416, in _rethrow[0m
[0;31m  exception:     return recv.get().unpickle()[0m
[0;31m  exception:   File "/home/travis/build/dw/mitogen/mitogen/core.py", line 595, in unpickle[0m
[0;31m  exception:     raise obj[0m
[0;31m  exception: CallError: exceptions.IOError: transfer of u'/tmp/tmp5j62F6' was interrupted.[0m
[0;31m  exception:   File "<stdin>", line 1993, in _dispatch_one[0m
[0;31m  exception:   File "master:/home/travis/build/dw/mitogen/ansible_mitogen/target.py", line 160, in transfer_file[0m
[0;31m  exception:     raise IOError('transfer of %r was interrupted.' % (in_path,))[0m
[0;31m  exception: [0m
[0;31m  failed: True[0m
[0;31m  msg: Unexpected failure during module execution.[0m
[0;31m}[0m
[0;31m[0m
[0;31mERROR! [pid 6803] 20:19:21.756986 E mitogen.ctx.ssh.localhost:2202: mitogen: get_file(u'/tmp/tmpCJ9Zys'): receiver was closed early, controller is likely shutting down.[0m
[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was:     raise IOError('transfer of %r was interrupted.' % (in_path,))[0m
[0;31mfatal: /home/travis/build/dw/mitogen/tests/ansible/integration/action/copy.yml:44: [target-centos6]: FAILED! => {[0m
[0;31m  exception: Traceback (most recent call last):[0m
[0;31m  exception:   File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/ansible/executor/task_executor.py", line 148, in run[0m
[0;31m  exception:     res = self._execute()[0m
[0;31m  exception:   File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/ansible/executor/task_executor.py", line 551, in _execute[0m
[0;31m  exception:     result = self._handler.run(task_vars=variables)[0m
[0;31m  exception:   File "/home/travis/build/dw/mitogen/ansible_mitogen/mixins.py", line 116, in run[0m
[0;31m  exception:     return super(ActionModuleMixin, self).run(tmp, task_vars)[0m
[0;31m  exception:   File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/ansible/plugins/action/copy.py", line 516, in run[0m
[0;31m  exception:     module_return = self._copy_file(source_full, source_rel, content, content_tempfile, dest, task_vars, tmp, delete_remote_tmp)[0m
[0;31m  exception:   File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/ansible/plugins/action/copy.py", line 273, in _copy_file[0m
[0;31m  exception:     remote_path = self._transfer_file(source_full, tmp_src)[0m
[0;31m  exception:   File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/ansible/plugins/action/__init__.py", line 310, in _transfer_file[0m
[0;31m  exception:     self._connection.put_file(local_path, remote_path)[0m
[0;31m  exception:   File "/home/travis/build/dw/mitogen/ansible_mitogen/connection.py", line 898, in put_file[0m
[0;31m  exception:     out_path=out_path[0m
[0;31m  exception:   File "/home/travis/build/dw/mitogen/ansible_mitogen/connection.py", line 429, in call[0m
[0;31m  exception:     return self._rethrow(recv)[0m
[0;31m  exception:   File "/home/travis/build/dw/mitogen/ansible_mitogen/connection.py", line 416, in _rethrow[0m
[0;31m  exception:     return recv.get().unpickle()[0m
[0;31m  exception:   File "/home/travis/build/dw/mitogen/mitogen/core.py", line 595, in unpickle[0m
[0;31m  exception:     raise obj[0m
[0;31m  exception: CallError: exceptions.IOError: transfer of u'/tmp/tmpCJ9Zys' was interrupted.[0m
[0;31m  exception:   File "<stdin>", line 1993, in _dispatch_one[0m
[0;31m  exception:   File "master:/home/travis/build/dw/mitogen/ansible_mitogen/target.py", line 160, in transfer_file[0m
[0;31m  exception:     raise IOError('transfer of %r was interrupted.' % (in_path,))[0m
[0;31m  exception: [0m
[0;31m  failed: True[0m
[0;31m  msg: Unexpected failure during module execution.[0m
[0;31m}[0m
[0;31m[0m
[0;33mchanged: [target-centos7][0m

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
[0;31mtarget-centos6[0m             : [0;32mok=32  [0m [0;33mchanged=11  [0m unreachable=0    [0;31mfailed=1   [0m
[0;33mtarget-centos7[0m             : [0;32mok=37  [0m [0;33mchanged=14  [0m unreachable=0    failed=0   
[0;31mtarget-debian[0m              : [0;32mok=36  [0m [0;33mchanged=18  [0m unreachable=0    [0;31mfailed=1   [0m
````

**Comment by dw** [comment]
The reason this was a race is because if Worker A calls mkstemp(), register(), completes put_file(), and deletes the temporary file, Worker B never sees the duplicate name on disk.

So it is a question of scheduling whether B picks a unique name
