### ISSUE TITLE
ansible 2.7

### ISSUE THREAD

**Issue by ulrichSchreiner** [dw/mitogen#392]
hi,

i've updated my ansible container to 2.7, now i get the following error when i try to use mitogen:
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 139, in run
    res = self._execute()
  File "/usr/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 598, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python3.6/site-packages/ansible_mitogen/mixins.py", line 115, in run
    return super(ActionModuleMixin, self).run(tmp, task_vars)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/lib/python3.6/site-packages/ansible_mitogen/mixins.py", line 334, in _execute_module
    self._connection._connect()
  File "/usr/lib/python3.6/site-packages/ansible_mitogen/connection.py", line 527, in _connect
    stack=mitogen.utils.cast(list(stack)),
  File "/usr/lib/python3.6/site-packages/mitogen/core.py", line 1126, in call_service
    return recv.get().unpickle()
  File "/usr/lib/python3.6/site-packages/mitogen/core.py", line 487, in unpickle
    raise obj
mitogen.core.CallError: exceptions.ImportError: Master does not have u'ansible_mitogen.target'
  File "<stdin>", line 2049, in _dispatch_calls
  File "<stdin>", line 2033, in _dispatch_one
  File "<stdin>", line 367, in import_module
  File "<stdin>", line 791, in load_module
```
do you plan to support ansible 2.7?

**Comment by ulrichSchreiner** [comment]
hi,
i tested it with `master` and it seems to has already been fixed.

**Comment by dw** [comment]
This is now on the stable branch and part of the brand nwe 0.2.3 release. To be updated when a new release is made, subscribe to https://www.freelists.org/list/mitogen-announce

Thanks for reporting this!
