### ISSUE TITLE
Mitogen not work in python 2.4

### ISSUE THREAD

**Issue by whky** [dw/mitogen#408]
When try to make a ssh connection with mitogen this error: 

2018-10-17 07:44:13,115 - mitogen - DEBUG - mitogen.ssh.Stream('local.19488').connect(): child process stdin/stdout=10
2018-10-17 07:44:13,233 - mitogen - DEBUG - mitogen.ssh.Stream('local.19488'): received b'MITO000\n'
2018-10-17 07:44:13,233 - mitogen - DEBUG - mitogen.ssh.Stream('local.19488')._ec0_received()
2018-10-17 07:44:13,245 - mitogen - DEBUG - register(Context(1, 'ssh.10.10.195.27'), mitogen.ssh.Stream('ssh.10.10.195.27'))
2018-10-17 07:44:13,246 - mitogen - DEBUG - Context(1, 'ssh.10.10.195.27').call_async(): monitor.core.get_measures_usage(Sender(Context(0, None), 1000))
2018-10-17 07:44:13,246 - mitogen - DEBUG - Context(1, 'ssh.10.10.195.27').send_async(Message(1, 0, 0, 101, 1001, b'\x80\x02(X\x0c\x00\x00\x00monitor.coreq\x00NX\x12\x00\x00\x00get_measures_usageq\x01cm'..131))
2018-10-17 07:44:13,266 - mitogen - DEBUG - mitogen.parent.TtyLogStream('ssh.10.10.195.27'):  'Traceback (most recent call last):'
2018-10-17 07:44:13,306 - mitogen - DEBUG - mitogen.parent.TtyLogStream('ssh.10.10.195.27'):  '  File "<stdin>", line 2093, in ?'
2018-10-17 07:44:13,306 - mitogen - DEBUG - mitogen.parent.TtyLogStream('ssh.10.10.195.27'):  '  File "<stdin>", line 2063, in main'
2018-10-17 07:44:13,306 - mitogen - DEBUG - mitogen.parent.TtyLogStream('ssh.10.10.195.27'):  '  File "<stdin>", line 1899, in _setup_master'
2018-10-17 07:44:13,306 - mitogen - DEBUG - mitogen.parent.TtyLogStream('ssh.10.10.195.27'):  '  File "<stdin>", line 1748, in __init__'
2018-10-17 07:44:13,307 - mitogen - DEBUG - mitogen.parent.TtyLogStream('ssh.10.10.195.27'):  "AttributeError: 'Thread' object has no attribute 'ident'"

--------------------

* I am using the last master version.
* Host OS ubuntu 16.04 and target OS RH5
* Host python version 3.6 and target Python version 2.4.3

**Comment by dw** [comment]
Hello, sorry for the crazy delay replying to this :)   `dmw` branch contains fixes for 2.4 support. Unfortunately there is no CI for this version yet, mostly because everyone has given up supporting it, but I still take the compatibility commitment seriously.

The full test suite isn't running for it yet, but basic SSH/etc. support should function now. I will try to get this merged to master for the coming week.

Thanks for reporting this.

**Comment by dw** [comment]
I have added Python 2.4 to the list of missing CI targets in #461.


This is now on the master branch and will make it into the next release. To be updated when a new release is made, subscribe to https://www.freelists.org/list/mitogen-announce

Thanks for reporting this!
