### ISSUE TITLE
Bad file descriptor in child context during repeat runs of StreamErrorTest.test_via_enoent

### ISSUE THREAD

**Issue by dw** [dw/mitogen#417]
````
python tests/parent_test.py  -vf StreamErrorTest.test_via_enoent StreamErrorTest.test_via_enoent StreamErrorTest.test_via_enoent StreamErrorTest.test_via_enoent StreamErrorTest.test_via_enoent StreamErrorTest.test_via_enoent StreamErrorTest.test_via_enoent StreamErrorTest.test_via_enoent StreamErrorTest.test_via_enoent
test_via_enoent (__main__.StreamErrorTest) ... ok
test_via_enoent (__main__.StreamErrorTest) ... ok
test_via_enoent (__main__.StreamErrorTest) ... ok
test_via_enoent (__main__.StreamErrorTest) ... ok
test_via_enoent (__main__.StreamErrorTest) ... ok
test_via_enoent (__main__.StreamErrorTest) ... ok
test_via_enoent (__main__.StreamErrorTest) ... ok
test_via_enoent (__main__.StreamErrorTest) ... ok
test_via_enoent (__main__.StreamErrorTest) ... 19:09:49.473710 E mitogen.ctx.fork.23771: mitogen: ExternalContext.main() crashed
Traceback (most recent call last):
  File "/Users/dmw/src/mitogen/mitogen/core.py", line 2836, in main
    self.dispatcher.run()
  File "/Users/dmw/src/mitogen/mitogen/core.py", line 2596, in run
    _profile_hook('main', self._dispatch_calls)
  File "/Users/dmw/src/mitogen/mitogen/core.py", line 460, in <lambda>
    _profile_hook = lambda name, func, *args: func(*args)
  File "/Users/dmw/src/mitogen/mitogen/core.py", line 2584, in _dispatch_calls
    for msg in self.recv:
  File "/Users/dmw/src/mitogen/mitogen/core.py", line 868, in __iter__
    msg = self.get(throw_dead=False)
  File "/Users/dmw/src/mitogen/mitogen/core.py", line 854, in get
    msg = self._latch.get(timeout=timeout, block=block)
  File "/Users/dmw/src/mitogen/mitogen/core.py", line 1825, in get
    return self._get_sleep(poller, timeout, block, rsock, wsock, cookie)
  File "/Users/dmw/src/mitogen/mitogen/core.py", line 1851, in _get_sleep
    raise e or TimeoutError()
OSError: [Errno 9] Bad file descriptor
````

**Comment by dw** [comment]
This is (almost) certainly due to a socket object we dupped the FD of and close()'d eventually getting GC'd and closing a reused file descriptor number.
