### ISSUE TITLE
test_context_shutdown does not raise OSError on 3.x

### ISSUE THREAD

**Issue by dw** [dw/mitogen#423]
```
======================================================================
FAIL: test_context_shutdown (parent_test.ContextTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dw/mitogen/tests/parent_test.py", line 179, in test_context_shutdown
    self.assertRaises(OSError, lambda: os.kill(pid, 0))
  File "/home/travis/build/dw/mitogen/tests/testlib.py", line 321, in assertRaises
    assert 0, '%r did not raise %r' % (func, exc)
AssertionError: <function ContextTest.test_context_shutdown.<locals>.<lambda> at 0x7fc2cf95df28> did not raise <class 'OSError'>
----------------------------------------------------------------------
Ran 372 tests in 37.624s
FAILED (failures=1, skipped=42)
```

https://travis-ci.org/dw/mitogen/jobs/451194607

````
test_context_shutdown (parent_test.ContextTest) ... 03:31:23.621366 D mitogen: mitogen.parent.Stream('default').connect()
03:31:23.632763 D mitogen: create_child() child 5687 fd 9, parent 5331, cmd: /home/travis/virtualenv/python3.6.3/bin/python -c "import codecs,os,sys;_=codecs.decode;exec(_(_(\"eNqFkcFPwyAYxc/rX9EbkNGNrt2cTZpodjAejElj3EEXA4Uq2gGh3er868dak7Xz4Invl/fgvfBleJ3qamKkERB5Fjc9koXvoND2C6LEG7mZ78wMEhwSgs6c4T5Zp4Yd56WuBMz6YPuw7kPjwAVWBxdf0tqlbv009QGntpEK+FTxVhTfIt/VlJWilae7yk6ZVFNzqD+0Aq7n6MI2TtuLe2ErqdVLEm3aWKH20joGt9ndMwGbdHit8zgs4VDAQxwDuJW1fhcqqS3dy+qmO4JPzQKax6yYLWgQ0TAP4qhYBCwuloFYXrGIz/mMsTiZR1GIAPJcXmNlLWCIwcP90yMh5FUB1zPX3K0Deav0DZ4WwrURyq0BWAbQxArKYRgtyDXC4Eca91Jh0rNvjUHDwGlHhfkNWLVz9+8X7uY/99+W4aDlEVe9uVM=\".encode(),\"base64\"),\"zip\"))"
03:31:23.634349 D mitogen: mitogen.parent.Stream('local.5687').connect(): stdin=9, stdout=8, diag=None
03:31:23.665558 D mitogen: mitogen.parent.Stream('local.5687')._ec0_received()
03:31:23.676155 D mitogen: register(Context(1, 'local.5687'), mitogen.parent.Stream('local.5687'))
03:31:23.676702 D mitogen: CallChain(Context(1, 'local.5687')).call_async(): posix.getpid()
03:31:23.677525 D mitogen: Context(1, 'local.5687').send_async(Message(1, 0, 0, 101, 1000, b'\x80\x02(NX\x05\x00\x00\x00posixq\x00NX\x06\x00\x00\x00getpidq\x01)cmitogen.core\nKwarg'..67))
03:31:23.744198 D mitogen: Context(1, 'local.5687').shutdown() sending SHUTDOWN
03:31:23.746302 D mitogen.ctx.local.5687: mitogen: Waker(Broker(0x7f91b8d9f4e0) rfd=3, wfd=4).on_disconnect()
03:31:23.746647 D mitogen: mitogen.parent.Stream('local.5687').on_disconnect()
03:31:23.747235 D mitogen: RouteMonitor(): mitogen.parent.Stream('local.5687') is gone; propagating DEL_ROUTE for {1}
03:31:23.747478 D mitogen: Router(Broker(0x7fc2cf95ea90)).del_route(1)
03:31:23.748142 D mitogen: Broker(0x7fc2cf95ea90).shutdown()
03:31:23.748428 D mitogen: mitogen.parent.Stream('local.5687'): PID 5687 exited due to signal 15 (SIGTERM)
03:31:23.748752 D mitogen: Waker(Broker(0x7fc2cf95ea90) rfd=4, wfd=5).on_shutdown()
03:31:23.748985 D mitogen: Waker(Broker(0x7fc2cf95ea90) rfd=4, wfd=5).on_disconnect()
FAIL

````

**Comment by dw** [comment]
No longer manifests.
