### ISSUE TITLE
Python 3.7: refusing to serve stdlib module 'pathlib'

### ISSUE THREAD

**Issue by dw** [dw/mitogen#440]
````
[02:42:42 u1804!8 mitogen] cat a.py

import pathlib

def x():
    return repr(pathlib.Path())
[02:42:43 u1804!9 mitogen]
[02:42:44 u1804!9 mitogen]
[02:42:44 u1804!9 mitogen]
[02:42:44 u1804!9 mitogen]
[02:42:45 u1804!9 mitogen] fg
python3.7


>>> l = r.ssh(hostname='localhost')
>>> l.call(a.x)
02:43:00.541016 W mitogen: ModuleResponder(Router(Broker(0x7f8778135588))): refusing to serve stdlib module 'pathlib'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dmw/src/mitogen/mitogen/parent.py", line 1508, in call
    return self.default_call_chain.call(fn, *args, **kwargs)
  File "/home/dmw/src/mitogen/mitogen/parent.py", line 1470, in call
    return receiver.get().unpickle(throw_dead=False)
  File "/home/dmw/src/mitogen/mitogen/core.py", line 692, in unpickle
    raise obj
mitogen.core.CallError: exceptions.ImportError: Master does not have u'pathlib'
  File "<stdin>", line 2620, in _dispatch_one
  File "<stdin>", line 2607, in _parse_request
  File "<stdin>", line 491, in import_module
  File "<stdin>", line 1129, in load_module
  File "<string>", line 1, in <module>
  File "master:/home/dmw/src/mitogen/a.py", line 2, in <module>
    import pathlib
  File "<stdin>", line 1107, in load_module

>>>



````

**Comment by dw** [comment]
This isn't a bug, it's another confusing error message.

Importer should

1) Explain exactly why the stdlib import was refused -- it's because a cross-major-version stdlib module request happened, which means the python_path is incorrect, or the code is using 3.x or 2.x-only features in a cross-major-version design.

2) The error was buried in a log message. It should be returned as part of the negative import hit response, and raised as an exception by the child, so the error appears in the correct place.

**Comment by jamesob** [comment]
Also seeing this for master/client with same Python version (3.6.7):
```python
#!/usr/bin/env python3.6
import os
import sys
from pathlib import Path

import mitogen


def install_app():
    os.system('ls {}'.format(Path.home()))


@mitogen.main()
def main(router):
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)

    context = router.ssh(hostname=sys.argv[1])
    # context = router.fork()
    context.call(install_app)
```

When run:
```bash
Traceback (most recent call last):
  File "mitogen_demo.py", line 13, in <module>
    @mitogen.main()
  File "/home/james/.local/lib/python3.6/site-packages/mitogen/__init__.py", line 118, in wrapper
    func,
  File "/home/james/.local/lib/python3.6/site-packages/mitogen/core.py", line 561, in _profile_hook
    return func(*args)
  File "/home/james/.local/lib/python3.6/site-packages/mitogen/utils.py", line 159, in run_with_router
    return func(router, *args, **kwargs)
  File "mitogen_demo.py", line 21, in main
    context.call(install_app)
  File "/home/james/.local/lib/python3.6/site-packages/mitogen/parent.py", line 1759, in call
    return self.default_call_chain.call(fn, *args, **kwargs)
  File "/home/james/.local/lib/python3.6/site-packages/mitogen/parent.py", line 1718, in call
    return receiver.get().unpickle(throw_dead=False)
  File "/home/james/.local/lib/python3.6/site-packages/mitogen/core.py", line 835, in unpickle
    raise obj
mitogen.core.CallError: exceptions.ImportError: The Mitogen master process was unable to serve u'pathlib'. It may be a native Python extension, or it may be missing entirely. Check the importer debug logs on the master for more information.
  File "<stdin>", line 3099, in _dispatch_one
  File "<stdin>", line 3086, in _parse_request
  File "<stdin>", line 596, in import_module
  File "<stdin>", line 1357, in load_module
  File "<string>", line 1, in <module>
  File "master:mitogen_demo.py", line 4, in <module>
    from pathlib import Path
  File "<stdin>", line 1330, in load_module

```

**Comment by jamesob** [comment]
My issue ended up being user error; I should've realized the hashbang at the beginning of my script isn't conveyed to the client. When I invoked the example script above and added a version printout, I saw that it was being run with Python 2.7:
```
09:05:17.173728 I mitogen.ctx.ssh.james2: stdout: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
09:05:17.174210 I mitogen.ctx.ssh.james2: stdout: [GCC 7.3.0]
```

Using the `python_path` kwarg on `router.ssh` ended up fixing the script:
```python
context = router.ssh(
    hostname=sys.argv[1], python_path=['/usr/bin/env', 'python3'])
```

**Comment by dw** [comment]
At the very least, the active Python version should be reported in the logs generated by the bootstrap. There is a separate bug (#478) open for propagating the real ModuleResponder error to the target and then back as a CallError to the master. It's convoluted, but the result should be easier to understand failures of this sort
