### ISSUE TITLE
DockerizedSshDaemon requires Docker >= 1.13 (API >= 1.25)

### ISSUE THREAD

**Issue by moreati** [dw/mitogen#46]
TLDR: Ubuntu 17.04 ships with Docker 1.12.6 (API 1.24). Mitogen's test suite uses a feature (AutoRemove) that is only available in Docker 1.13 (API 1.25) and onward. 

Attempting to the `tests/fakessh_test.py` using the version of Docker shipped with Ubuntu 16.04 results in the the error

```
APIError: 400 Client Error: Bad Request ("client is newer than server (client API version: 1.30, server API version: 1.24)")
```

API version 1.30 is the default tried by docker-py 2.5.1, which is specified in `dev_requirements.txt`. docker-py can be made to use an API version supported by the server by applying

```diff
diff --git a/tests/testlib.py b/tests/testlib.py
index e60d21d..f49697f 100644
--- a/tests/testlib.py
+++ b/tests/testlib.py
@@ -42,7 +42,7 @@ class TestCase(unittest.TestCase):
 
 class DockerizedSshDaemon(object):
     def __init__(self):
-        self.docker = docker.from_env()
+        self.docker = docker.from_env(version='auto')
         self.container_name = 'mitogen-test-%08x' % (random.getrandbits(64),)
         self.container = self.docker.containers.run(
             image='d2mw/mitogen-test',
```

However this still results in a new error

```
:~/src/mitogen [venv] pytest-catchlog(+47/-3)+*± python tests/fakessh_test.py 
00:21:43 D docker.auth: Trying paths: ['/home/alex/.docker/config.json', '/home/alex/.dockercfg']
00:21:43 D docker.auth: No config file found
00:21:43 D urllib3.connectionpool: http://localhost:None "GET /version HTTP/1.1" 200 199
E
======================================================================
ERROR: setUpClass (__main__.RsyncTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/src/mitogen/tests/testlib.py", line 88, in setUpClass
    cls.dockerized_ssh = DockerizedSshDaemon()
  File "/home/alex/src/mitogen/tests/testlib.py", line 51, in __init__
    publish_all_ports=True,
  File "/home/alex/src/mitogen/venv/local/lib/python2.7/site-packages/docker/models/containers.py", line 697, in run
    raise RuntimeError("The options 'detach' and 'remove' cannot "
RuntimeError: The options 'detach' and 'remove' cannot be used together in api versions < 1.25.

----------------------------------------------------------------------
Ran 0 tests in 0.003s

FAILED (errors=1)
```

**Comment by moreati** [comment]
Feel free to close this as WONTFIX. I just wanted to document it for future travellers and googlers.

I'm upgrading to Ubuntu 16.10 to avoid it.

**Comment by dw** [comment]
I hit this one myself, not sure what to do about it. We could update tearDown() to just manually do the removal I suppose

**Comment by dw** [comment]
I've created a #mitogen IRC channel on Freenode if you'd like any help or pointers.. to say the least this isn't the friendliest code to work on in general, and in particular right now, so feel free to drop in
