### ISSUE TITLE
[0.2.4] double Broker.shutdown() during Ansible graceful shutdown

### ISSUE THREAD

**Issue by dw** [dw/mitogen#468]
````
[pid 18912] 08:02:12.625690 D mitogen.ctx.ssh.localhost: mitogen: mitogen.fork.Stream(u'fork.19081') closing CALL_FUNCTION channel
[pid 18912] 08:02:12.626143 I mitogen: mitogen.service.Pool(0x7fbf8a5e4d50, size=16, th='mitogen.service.Pool.7fbf8a5e4d50.worker-0'): channel or latch closed, exitting: None
[pid 18912] 08:02:12.627267 D mitogen.ctx.ssh.localhost: mitogen: mitogen.parent.DiagLogStream(fd=17, u'sudo.dmw').on_disconnect()
[pid 18912] 08:02:12.627751 D mitogen.ctx.ssh.localhost: mitogen: mitogen.sudo.Stream(u'sudo.dmw') closing CALL_FUNCTION channel
ERROR! [pid 18912] 08:02:12.627962 I mitogen.ctx.ssh.localhost: stderr: Traceback (most recent call last):
ERROR! [pid 18912] 08:02:12.628207 I mitogen.ctx.ssh.localhost: stderr:   File "<stdin>", line 3049, in <module>
ERROR! [pid 18912] 08:02:12.628355 I mitogen.ctx.ssh.localhost: stderr:   File "<stdin>", line 3046, in main
ERROR! [pid 18912] 08:02:12.628453 I mitogen.ctx.ssh.localhost: stderr:   File "<stdin>", line 2710, in shutdown
ERROR! [pid 18912] 08:02:12.628555 I mitogen.ctx.ssh.localhost: stderr:   File "<stdin>", line 2123, in defer
[pid 18912] 08:02:12.628644 D mitogen.ctx.ssh.localhost: mitogen: <IoLogger stdout>.on_disconnect()
[pid 18912] 08:02:12.628747 D mitogen.ctx.ssh.localhost: mitogen: <IoLogger stderr>.on_disconnect()
````

**Comment by dw** [comment]
Fixed generally by 5ef94eb3e28c09dfe5d128be34f40e42bc0dfb39
