### ISSUE TITLE
Python 3.7 breaks pkgutil ModuleFinder method

### ISSUE THREAD

**Issue by dw** [dw/mitogen#479]
Attempts to import `__main__` using pkgutil, fails, falls back on inspect.getsource() which is deeply unreliable, it in turn starts to randomly fail:

````
12:34:51.481700 D mitogen.ctx.local.72181: mitogen: ModuleForwarder(Router(Broker(0x10808ee48)))._on_get_module(Message(1, 4, 4, 100, 0, b'__main__'..8))
12:34:51.481799 D mitogen: ModuleResponder(Router(Broker(0x104c59128)))._on_get_module(b'__main__')
12:34:51.481946 D mitogen: ModuleFinder()._get_module_via_pkgutil('__main__'): Error while finding loader for '__main__' (<class 'ValueError'>: __main__.__spec__ is None)
12:34:51.482020 D mitogen: _get_module_via_sys_modules('__main__') -> <module '__main__' from 'content/push_demo.py'>
12:34:51.482239 D mitogen: While importing '__main__'
Traceback (most recent call last):
  File "/Users//env/lib/python3.7/site-packages/mitogen/master.py", line 694, in _send_module_and_related
    tup = self._build_tuple(fullname)
  File "/Users//env/lib/python3.7/site-packages/mitogen/master.py", line 636, in _build_tuple 
    path, source, is_pkg = self._finder.get_module_source(fullname)
  File "/Users//env/lib/python3.7/site-packages/mitogen/master.py", line 472, in get_module_source 
    tup = method(self, fullname)
  File "/Users//env/lib/python3.7/site-packages/mitogen/master.py", line 441, in _get_module_via_sys_modules
    source = inspect.getsource(module)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 968, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

````

**Comment by dw** [comment]
https://bugs.python.org/issue23389

**Comment by dw** [comment]
It broke multiprocessing too at some point https://bugs.python.org/issue19946

**Comment by dw** [comment]
https://github.com/unbit/uwsgi/issues/621

**Comment by dw** [comment]
https://docs.python.org/3/reference/import.html#special-considerations-for-main

**Comment by dw** [comment]
This manifests as a log message like:

````
16:11:46.167212 D mitogen: ModuleFinder()._get_module_via_pkgutil('__main__'): Error while finding loader for '__main__' (<class 'ValueError'>: __main__.__spec__ is None)
````

And if you're unlucky, a failure to import `__main__`.
