### ISSUE TITLE
ssh_debug_level=3 MITO000 problem

### ISSUE THREAD

**Issue by dw** [dw/mitogen#489]
The inherent raciness of this facility is already known, but this is a new one:

````

======================================================================
ERROR: test_accept_enforce_host_keys (ssh_test.SshTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dw/mitogen/tests/ssh_test.py", line 163, in test_accept_enforce_host_keys
    check_host_keys='accept',
  File "/home/travis/build/dw/mitogen/tests/testlib.py", line 467, in docker_ssh
    return self.router.ssh(**kwargs)
  File "/home/travis/build/dw/mitogen/mitogen/parent.py", line 2033, in ssh
    return self.connect(u'ssh', **kwargs)
  File "/home/travis/build/dw/mitogen/mitogen/parent.py", line 1981, in connect
    return self._connect(klass, name=name,
  File "/home/travis/build/dw/mitogen/mitogen/parent.py", line 1965, in _connect
    raise mitogen.core.StreamError(self.connection_timeout_msg)
StreamError: Connection timed out.

----------------------------------------------------------------------
Ran 432 tests in 113.101s

FAILED (errors=1, skipped=88)
````

Due to:

````
...
05:34:46 D mitogen: mitogen.ssh.Stream(u'local.5204'): debug3: Ignored env GEM_PATH
05:34:46 D mitogen: mitogen.ssh.Stream(u'local.5204'): debug3: Ignored env SSH_CONNECTION
05:34:46 D mitogen: mitogen.ssh.Stream(u'local.5204'): debug1:MITO000
````

There is explicit code to prevent that from happening, somehow the state machine matched MITO000 as if it were debug output

**Comment by dw** [comment]
Having seen this in 6 months, and in the interim the implementation got a huge rewrite during the stream-refactor branch. I'm reasonably sure this will never show up again
