### ISSUE TITLE
tests/ansible/tests/connection_test.py PutFile flakeyness

### ISSUE THREAD

**Issue by dw** [dw/mitogen#490]
Some very unhappy stack traces. Looks like Yet Another Forking Issue(tm), but most likely just constrained to the test suite:

````
16:56:47.387714 D mitogen: Context(0, None).send_async(Message(0, 1040, 1040, 110, 1002, "\x80\x02X'\x00\x00\x00ansible_mitogen.services.ContextServiceq\x01X\x03"..162))
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 892, in emit
    self.flush()
  File "/usr/lib/python2.7/logging/__init__.py", line 854, in flush
    self.release()
  File "/usr/lib/python2.7/logging/__init__.py", line 722, in release
    self.lock.release()
  File "/usr/lib/python2.7/threading.py", line 204, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
Logged from file core.py, line 1771
ERROR
ERROR
16:56:47.409649 E mitogen: defer() crashed: <bound method Router._async_route of Router(Broker(0x7f09f9b30050))>(*(Message(0, 1040, 1040, 110, 1001, '\x80\x02X\x1b\x00\x00\x00mitogen.service.FileServiceq\x01X\x08\x00\x00\x00registerq'..120),), **{})
Traceback (most recent call last):
  File "/home/dmw/src/mitogen/mitogen/core.py", line 2286, in on_receive
    func(*args, **kwargs)
  File "/home/dmw/src/mitogen/mitogen/core.py", line 2724, in _async_route
    out_stream._send(msg)
  File "/home/dmw/src/mitogen/mitogen/core.py", line 1683, in _send
    self._router.broker._start_transmit(self)
  File "/home/dmw/src/mitogen/mitogen/core.py", line 2805, in _start_transmit
    self.poller.start_transmit(side.fd, (side, stream.on_transmit))
  File "/home/dmw/src/mitogen/mitogen/parent.py", line 937, in start_transmit
    self._control(fd)
  File "/home/dmw/src/mitogen/mitogen/parent.py", line 916, in _control
    self._epoll.register(fd, mask)
IOError: [Errno 9] Bad file descriptor
16:56:47.426167 D mitogen: Broker(0x7f09f9b30050).shutdown()



````

**Comment by dw** [comment]
IO trace for one hang:

<details><summary>Log</summary>

````17:06:40.218647 D mitogen.io: EpollPoller(0x7f57d1d47110).start_receive(7, (<Side of Waker(Broker(0x7f57d1d3cfd0) rfd=7, wfd=8) fd 7>, <bound method Waker.on_receive of Waker(Broker(0x7f57d1d3cfd0) rfd=7, wfd=8)>))
17:06:40.218889 D mitogen.io: EpollPoller(0x7f57d1d47110)._control(7)
17:06:40.219320 D mitogen.io: Broker(0x7f57d1d3cfd0)._loop_once(None, EpollPoller(0x7f57d1d47110))
17:06:40.219624 D mitogen: unix.connect(path='/tmp/mitogen_unix_Tb3Lqv')
17:06:40.219791 D mitogen.io: EpollPoller(0x7f57d1d47110).poll(None)
17:06:40.220311 D mitogen.io: EpollPoller(0x7f57d1d0a9d0): POLLIN: 8
17:06:40.220863 D mitogen: unix.connect(): local ID is 1040, remote is 0
17:06:40.220943 D mitogen: register(Context(1040, None), mitogen.core.Stream(u'unix_client.10867'))
17:06:40.221148 D mitogen.io: Router(Broker(0x7f57d1d3cfd0)).add_handler(<bound method Router._on_del_route of Router(Broker(0x7f57d1d3cfd0))>, 104, True)
17:06:40.221165 D mitogen.io: Broker(0x7f57d1d0a650).start_receive(mitogen.core.Stream(u'unix_client.10867'))
17:06:40.221332 D mitogen.io: Router(Broker(0x7f57d1d3cfd0)).add_handler(<bound method IdAllocator.on_allocate_id of IdAllocator(Router(Broker(0x7f57d1d3cfd0)))>, 105, True)
17:06:40.221328 D mitogen.io: Waker(Broker(0x7f57d1d0a650) rfd=3, wfd=6).defer() [immediate]
17:06:40.221533 D mitogen.io: Router(Broker(0x7f57d1d3cfd0)).add_handler(<bound method ModuleResponder._on_get_module of ModuleResponder(Router(Broker(0x7f57d1d3cfd0)))>, 100, True)
17:06:40.221523 D mitogen.io: EpollPoller(0x7f57d1d0a9d0).start_receive(14, (<Side of mitogen.core.Stream(u'unix_client.10867') fd 14>, <bound method Stream.on_receive of mitogen.core.Stream(u'unix_client.10867')>))
17:06:40.221708 D mitogen.io: Router(Broker(0x7f57d1d3cfd0)).add_handler(<bound method LogForwarder._on_forward_log of LogForwarder(Router(Broker(0x7f57d1d3cfd0)))>, 102, True)
17:06:40.221722 D mitogen.io: EpollPoller(0x7f57d1d0a9d0)._control(14)
17:06:40.221877 D mitogen.io: Router(Broker(0x7f57d1d3cfd0)).add_handler(<bound method RouteMonitor._on_add_route of RouteMonitor()>, 103, True)
17:06:40.221931 D mitogen.io: Broker(0x7f57d1d0a650)._loop_once(None, EpollPoller(0x7f57d1d0a9d0))
17:06:40.222012 D mitogen.io: Router(Broker(0x7f57d1d3cfd0)).add_handler(<bound method RouteMonitor._on_del_route of RouteMonitor()>, 104, True)
17:06:40.222103 D mitogen.io: EpollPoller(0x7f57d1d0a9d0).poll(None)
17:06:40.222166 D mitogen.io: Router(Broker(0x7f57d1d3cfd0)).add_handler(<bound method Router._on_detaching of Router(Broker(0x7f57d1d3cfd0))>, 109, True)
17:06:40.222494 D mitogen: register(Context(0, None), mitogen.core.Stream(u'unix_listener.10870'))
17:06:40.222687 D mitogen.io: Broker(0x7f57d1d3cfd0).start_receive(mitogen.core.Stream(u'unix_listener.10870'))
17:06:40.222879 D mitogen.io: Waker(Broker(0x7f57d1d3cfd0) rfd=7, wfd=8).defer() [fd=8]
17:06:40.223310 D mitogen: Context(0, None).call_service_async(u'ansible_mitogen.services.ContextService', u'get', {'stack': [{u'method': u'local', u'kwargs': {u'python_path': None}}]})
17:06:40.228652 D mitogen.io: EpollPoller(0x7f57d1d47110): POLLIN: 7
17:06:40.229326 D mitogen.io: <Side of Waker(Broker(0x7f57d1d3cfd0) rfd=7, wfd=8) fd 7>.close()
17:06:40.229592 D mitogen.io: Waker(Broker(0x7f57d1d3cfd0) rfd=7, wfd=8).on_receive()
17:06:40.230287 D mitogen.io: <Side of mitogen.core.Stream(u'unix_listener.10870') fd 13>.close()
17:06:40.230639 D mitogen.io: EpollPoller(0x7f57d1d47110).start_receive(12, (<Side of mitogen.core.Stream(u'unix_listener.10870') fd 12>, <bound method Stream.on_receive of mitogen.core.Stream(u'unix_listener.10870')>))
17:06:40.231243 D mitogen.io: <Side of mitogen.core.Stream(u'unix_listener.10870') fd 12>.close()
17:06:40.231471 D mitogen.io: EpollPoller(0x7f57d1d47110)._control(12)
17:06:40.231867 D mitogen.io: EpollPoller(0x7f57d1d0a9d0): POLLIN: 14
17:06:40.232204 D mitogen.io: mitogen.core.Stream(u'unix_client.10867').on_receive()
17:06:40.231955 D mitogen.io: <Side of Waker(Broker(0x7f57d1d3cfd0) rfd=7, wfd=8) fd 8>.close()
17:06:40.232489 D mitogen: mitogen.core.Stream(u'unix_client.10867').on_disconnect()
17:06:40.232692 D mitogen.io: Broker(0x7f57d1d0a650).stop_receive(mitogen.core.Stream(u'unix_client.10867'))
17:06:40.232864 D mitogen.io: Waker(Broker(0x7f57d1d0a650) rfd=3, wfd=6).defer() [immediate]
17:06:40.233051 D mitogen.io: EpollPoller(0x7f57d1d0a9d0).stop_receive(14)
17:06:40.233186 D mitogen.io: EpollPoller(0x7f57d1d0a9d0)._control(14)
17:06:40.233343 D mitogen.io: <Side of mitogen.core.Stream(u'unix_client.10867') fd 14>.close()
17:06:40.233543 D mitogen.io: Broker(0x7f57d1d0a650)._stop_transmit(mitogen.core.Stream(u'unix_client.10867'))
17:06:40.233709 D mitogen.io: EpollPoller(0x7f57d1d0a9d0).stop_transmit(16)
17:06:40.233848 D mitogen.io: EpollPoller(0x7f57d1d0a9d0)._control(16)
17:06:40.233999 D mitogen.io: <Side of mitogen.core.Stream(u'unix_client.10867') fd 16>.close()
17:06:40.234251 D mitogen: Context(1040, None).on_disconnect()
17:06:40.234481 D mitogen.io: Broker(0x7f57d1d0a650)._loop_once(None, EpollPoller(0x7f57d1d0a9d0))
17:06:40.234648 D mitogen.io: EpollPoller(0x7f57d1d0a9d0).poll(None)
17:06:40.247719 D mitogen.io: Router(Broker(0x7f57d1d3cfd0)).add_handler(<bound method Receiver._on_receive of Receiver(Router(Broker(0x7f57d1d3cfd0)), None)>, 1000, False)
17:06:40.248084 D mitogen: Context(0, None).send_async(Message(0, 1040, 1040, 110, 1000, "\x80\x02X'\x00\x00\x00ansible_mitogen.services.ContextServiceq\x01X\x03"..172))
17:06:40.248277 D mitogen.io: Waker(Broker(0x7f57d1d3cfd0) rfd=7, wfd=8).defer() [fd=8]
17:06:40.248457 D mitogen.io: Receiver(Router(Broker(0x7f57d1d3cfd0)), 1000).get(timeout=None, block=True)
17:06:40.248666 D mitogen.io: Latch(0x7f57d1d25d90, size=0, t='MainThread').get(timeout=None, block=True)
17:06:40.249020 D mitogen.io: Latch(0x7f57d1d25d90, size=0, t='MainThread')._get_sleep(timeout=None, block=True, rfd=8, wfd=10)
17:06:40.249222 D mitogen.io: Poller(0x7f57d1d25cd0).poll(None)
17:06:40.232229 E mitogen: defer() crashed: <bound method EpollPoller.start_receive of EpollPoller(0x7f57d1d47110)>(*(12, (<Side of mitogen.core.Stream(u'unix_listener.10870') fd 12>, <bound method Stream.on_receive of mitogen.core.Stream(u'unix_listener.10870')>)), **{})
Traceback (most recent call last):
  File "/home/dmw/src/mitogen/mitogen/core.py", line 2286, in on_receive
    func(*args, **kwargs)
  File "/home/dmw/src/mitogen/mitogen/parent.py", line 926, in start_receive
    self._control(fd)
  File "/home/dmw/src/mitogen/mitogen/parent.py", line 916, in _control
    self._epoll.register(fd, mask)
IOError: [Errno 9] Bad file descriptor
17:06:40.250730 E mitogen: Waker(Broker(0x7f57d1d3cfd0) rfd=7, wfd=8) crashed
Traceback (most recent call last):
  File "/home/dmw/src/mitogen/mitogen/core.py", line 2851, in _call
    func(self)
  File "/home/dmw/src/mitogen/mitogen/core.py", line 2289, in on_receive
    func, args, kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1207, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1200, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1293, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 768, in handle
    self.release()
  File "/usr/lib/python2.7/logging/__init__.py", line 722, in release
    self.lock.release()
  File "/usr/lib/python2.7/threading.py", line 204, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
17:06:40.252385 D mitogen: Waker(Broker(0x7f57d1d3cfd0) rfd=7, wfd=8).on_disconnect()
17:06:40.252599 D mitogen.io: Broker(0x7f57d1d3cfd0).stop_receive(Waker(Broker(0x7f57d1d3cfd0) rfd=7, wfd=8))
17:06:40.252762 D mitogen.io: Waker(Broker(0x7f57d1d3cfd0) rfd=7, wfd=8).defer() [immediate]
17:06:40.252924 D mitogen.io: EpollPoller(0x7f57d1d47110).stop_receive(7)
17:06:40.253060 D mitogen.io: EpollPoller(0x7f57d1d47110)._control(7)
17:06:40.253198 D mitogen.io: Broker(0x7f57d1d3cfd0)._stop_transmit(Waker(Broker(0x7f57d1d3cfd0) rfd=7, wfd=8))
17:06:40.253330 D mitogen.io: EpollPoller(0x7f57d1d47110).stop_transmit(8)
17:06:40.253451 D mitogen.io: EpollPoller(0x7f57d1d47110)._control(8)
17:06:40.253607 D mitogen.io: Broker(0x7f57d1d3cfd0)._loop_once(None, EpollPoller(0x7f57d1d47110))
17:06:40.253736 D mitogen.io: EpollPoller(0x7f57d1d47110).poll(None)
````

</details>

**Comment by dw** [comment]
It looks like some asynchrony issue with Connection.close()

**Comment by dw** [comment]
it's due to the call to `mitogen.fork.on_fork()`! So this is an asynchrony issue

**Comment by dw** [comment]
Useful learnings: "attempt to release unacquired lock" and "bad file descriptor" are  strong indicators on_fork() was called at the wrong moment.
