### ISSUE TITLE
[0.2.4] FileService.acknowledge race

### ISSUE THREAD

**Issue by dw** [dw/mitogen#504]
with taskset -c -p 1

````
[15:35:59 eldil!8 mitogen] python tests/bench/throughput.py 
Testing local()...
local() took 1555.64 ms to transfer 512.00 MiB, 329.12 MiB/s
15:36:04.454017 E mitogen: While calling no-reply method FileService.acknowledge
Traceback (most recent call last):
  File "/home/dmw/src/mitogen/mitogen/service.py", line 254, in _invoke
    ret = method(**kwargs)
  File "/home/dmw/src/mitogen/mitogen/service.py", line 976, in acknowledge
    state = self._state_by_stream[stream]
KeyError: None
````

**Comment by dw** [comment]
It's harmless, the race is since there is no guarantee service pool threads will ever have a chance to process acknowledge() calls before another thread disconnects the stream, which is exactly what's happening here.

Might need to add a few more stream_connect/stream_disconnect signals to give FileService a place where it can robust create/forget state relating to a stream
