### ISSUE TITLE
SshTest: ssh_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by moreati** [dw/mitogen#51]
While running the unit tests on my laptop, in Ubuntu 17.10 beta (Artful Aardvark) I am seeing tests in `tests/ssh_test.py` fail while trying to connect, e.g.

```
$ PYTHONPATH=. python tests/ssh_test.py 
.E....F.
======================================================================
ERROR: test_password_incorrect (__main__.SshTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/ssh_test.py", line 63, in test_password_incorrect
    password='badpw',
  File "/home/alex/src/mitogen/tests/testlib.py", line 99, in docker_ssh
    return self.router.ssh(**kwargs)
  File "/home/alex/src/mitogen/mitogen/master.py", line 938, in ssh
    return self.connect('ssh', **kwargs)
  File "/home/alex/src/mitogen/mitogen/master.py", line 959, in connect
    return self._connect(context_id, klass, name=name, **kwargs)
  File "/home/alex/src/mitogen/mitogen/master.py", line 945, in _connect
    stream.connect()
  File "/home/alex/src/mitogen/mitogen/ssh.py", line 68, in connect
    super(Stream, self).connect()
  File "/home/alex/src/mitogen/mitogen/master.py", line 760, in connect
    self._connect_bootstrap()
  File "/home/alex/src/mitogen/mitogen/ssh.py", line 80, in _connect_bootstrap
    time.time() + 10.0):
  File "/home/alex/src/mitogen/mitogen/master.py", line 182, in iter_read
    (''.join(bits)[-300:],)
StreamError: EOF on stream; last 300 bytes received: 'ssh_exchange_identification: Connection closed by remote host\r\n'
...
```
The failures are not 100% consistent. I've seen the following variations

- "Connection _reset_ by remote host", rather than "Connection closed by remote host"
- Different tests (e.g. SshTest.pubkey_required, SshTest.pubkey_specified) exhibiting the error

Investigations so far.
- Rebuilding the Docker image on debian:unstable, ubuntu:zesty, or ubuntu:artful has not not fixed it.
- Setting `TCPKeepAlive=no` has not fixed it
- Running the same test in a 17.10 beta VM has not reproduced it so far

**Comment by moreati** [comment]
A probably unrelated detail. I found my `.ssh/known_hosts` had a line consisting of the string "Needs output, otherwise thinks ssh-keyscan timed out'" repeated a number of times. That appears to have originated from running Ansible unit tests on another occasion.

Fixing my known_hosts did not fix this issue.

**Comment by moreati** [comment]
This looks like a race condition. I think ssh is trying to connect/authenticate before sshd has completely started. As a workaround `time.sleep(5.0)` adding in `DockerMixin.setupClass()` allows these tests to complete without errors.

Pull request to follow, once I've read up on `socket.connect()` and timeouts.
