### ISSUE TITLE
Waker(Broker()) crashed

### ISSUE THREAD

**Issue by roidelapluie** [dw/mitogen#552]
Have you seen  this error before?

14:46:41 ERROR! [pid 10451] 14:46:41.566824 E mitogen: Waker(Broker(0x7f5bfcbe9750) rfd=20, wfd=21) crashed
14:46:41 Traceback (most recent call last):
14:46:41   File "/nexus/jenkins/jobs/ansible/jobs/pil-exec/workspace/mitogen/mitogen/core.py", line 2931, in _call
14:46:41     func(self)
14:46:41   File "/nexus/jenkins/jobs/ansible/jobs/pil-exec/workspace/mitogen/mitogen/core.py", line 2327, in on_receive
14:46:41     self.receive_side.read(1)
14:46:41   File "/nexus/jenkins/jobs/ansible/jobs/pil-exec/workspace/mitogen/mitogen/core.py", line 1486, in read
14:46:41     s, disconnected = io_op(os.read, self.fd, n)
14:46:41   File "/nexus/jenkins/jobs/ansible/jobs/pil-exec/workspace/mitogen/mitogen/core.py", line 473, in io_op
14:46:41     return func(*args), None
14:46:41 OSError: [Errno 9] Bad file descriptor

**Comment by dw** [comment]
Not in a very long time. Did it happen near the end of the job?

**Comment by dw** [comment]
I wonder if it's coming from a worker process, or the connection multiplexer process. The low FD number suggests this is a worker.

How many targets were in your run?
