### ISSUE TITLE
Azure Pipelines random failure

### ISSUE THREAD

**Issue by dw** [dw/mitogen#553]
Python 3.6 -> Python 2.6

````
test_tuple (utils_test.CastTest) ... ok
test_unicode (utils_test.CastTest) ... ok
test_unknown (utils_test.CastTest) ... ok
test_run_with_broker (utils_test.RunWithRouterTest) ... 16:23:08.197842 D mitogen: Broker(0x7efd51c3df98).shutdown()
16:23:08.198162 D mitogen: Waker(Broker(0x7efd51c3df98) rfd=3, wfd=4).on_shutdown()
16:23:08.198626 D mitogen: Waker(Broker(0x7efd51c3df98) rfd=3, wfd=4).on_disconnect()
16:23:08.199080 D mitogen: Router(Broker(0x7efd51c3df98)): stats: 0 module requests in 0 ms, 0 sent (0 ms minify time), 0 negative responses. Sent 0.0 kb total, 0.0 kb avg.
ok
test_with_broker (utils_test.WithRouterTest) ... 16:23:08.200959 D mitogen: Broker(0x7efd5ab49f28).shutdown()
16:23:08.201232 D mitogen: Waker(Broker(0x7efd5ab49f28) rfd=3, wfd=4).on_shutdown()
16:23:08.201432 D mitogen: Waker(Broker(0x7efd5ab49f28) rfd=3, wfd=4).on_disconnect()
16:23:08.201707 D mitogen: Router(Broker(0x7efd5ab49f28)): stats: 0 module requests in 0 ms, 0 sent (0 ms minify time), 0 negative responses. Sent 0.0 kb total, 0.0 kb avg.
ok

======================================================================
FAIL: test_exception (broker_test.DeferSyncTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vsts/work/1/s/tests/testlib.py", line 338, in tearDown
    self._teardown_check_fds()
  File "/home/vsts/work/1/s/tests/testlib.py", line 333, in _teardown_check_fds
    self, self._fd_count_before, get_fd_count(),
AssertionError: test_exception (broker_test.DeferSyncTest) leaked FDs. Count before: 4, after: 4

----------------------------------------------------------------------
Ran 506 tests in 80.786s

FAILED (failures=1, skipped=45)
coverage report is at file:///home/vsts/work/1/s/htmlcov/index.html
Command exited with non-zero status 1
35.21user 2.65system 1:25.49elapsed 44%CPU (0avgtext+0avgdata 60112maxresident)k
9600inputs+6784outputs (23major+793065minor)pagefaults 0swaps
Running: ['/usr/bin/time', '--', './run_tests', '-v']
Traceback (most recent call last):
  File ".ci/mitogen_tests.py", line 17, in <module>
    ci_lib.run('./run_tests -v')
  File "/home/vsts/work/1/s/.ci/ci_lib.py", line 89, in run
    ret = subprocess.check_call(argv, **kwargs)
  File "/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/time', '--', './run_tests', '-v']' returned non-zero exit status 1.
##[error]Bash exited with code '1'.
##[section]Finishing: Run tests.
````

**Comment by dw** [comment]
I have no idea how this is happening. That code should not run until the broker is (synchronously) completely shut down. The error suggests get_fd_count() returned >= 4 just a moment previously, so it's racing with some component that is shutting down
