### ISSUE TITLE
New traceback with 0.2.5 - error: integer out of range for 'L' format code

### ISSUE THREAD

**Issue by opoplawski** [dw/mitogen#557]
* Which version of Ansible are you running?
ansible-2.7.8-1.el7.noarch

* Have you tried the latest master version from Git?
no

* Mention your host and target OS and versions
ansible-pull on CentOS 7.6

This is new with 0.2.5:
```
TASK [Gathering Facts] *********************************************************
Wednesday 06 March 2019  07:43:03 -0800 (0:00:00.248)       0:00:00.248 *******
ERROR! [pid 367380] 07:43:03.734398 E mitogen: mitogen.service.Pool(0x7f21a60d18d0, size=32, th='mitogen.service.Pool.7f21a60d18d0.worker-0'): while invoking u'get' of u'ansible_mitogen.services.ContextService'
Traceback (most recent call last):
File "/root/.ansible/pull/kronos.mry.nwra.com/mitogen-0.2.5/mitogen/service.py", line 544, in _on_service_call
return invoker.invoke(method_name, kwargs, msg)
File "/root/.ansible/pull/kronos.mry.nwra.com/mitogen-0.2.5/mitogen/service.py", line 274, in invoke
response = self._invoke(method_name, kwargs, msg)
File "/root/.ansible/pull/kronos.mry.nwra.com/mitogen-0.2.5/mitogen/service.py", line 260, in _invoke
ret = method(**kwargs)
File "/root/.ansible/pull/kronos.mry.nwra.com/mitogen-0.2.5/ansible_mitogen/services.py", line 467, in get
reraise(*result)
File "/root/.ansible/pull/kronos.mry.nwra.com/mitogen-0.2.5/ansible_mitogen/services.py", line 425, in _wait_or_start
response = self._connect(key, spec, via=via)
File "/root/.ansible/pull/kronos.mry.nwra.com/mitogen-0.2.5/ansible_mitogen/services.py", line 377, in _connect
context = method(via=via, unidirectional=True, **spec['kwargs'])
File "/root/.ansible/pull/kronos.mry.nwra.com/mitogen-0.2.5/mitogen/parent.py", line 2134, in local
return self.connect(u'local', **kwargs)
File "/root/.ansible/pull/kronos.mry.nwra.com/mitogen-0.2.5/mitogen/parent.py", line 2097, in connect
**mitogen.core.Kwargs(kwargs))
File "/root/.ansible/pull/kronos.mry.nwra.com/mitogen-0.2.5/mitogen/parent.py", line 2078, in _connect
stream.connect()
File "/root/.ansible/pull/kronos.mry.nwra.com/mitogen-0.2.5/mitogen/parent.py", line 1380, in connect
self.pid, fd, diag_fd = self.start_child()
File "/root/.ansible/pull/kronos.mry.nwra.com/mitogen-0.2.5/mitogen/parent.py", line 1354, in start_child
return self.create_child(args, **self.create_child_args)
File "/root/.ansible/pull/kronos.mry.nwra.com/mitogen-0.2.5/mitogen/parent.py", line 350, in create_child
**extra
File "/root/.ansible/pull/kronos.mry.nwra.com/mitogen-0.2.5/mitogen/parent.py", line 302, in detach_popen
proc = subprocess.Popen(preexec_fn=preexec_fn, **kwargs)
File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
errread, errwrite)
File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
raise child_exception
error: integer out of range for 'L' format code
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:     raise child_exception
```

**Comment by opoplawski** [comment]
Only seeing this on a few hosts so far.

**Comment by dw** [comment]
Most likely they're 32 bit hosts.. I've quite literally just pushed 0.2.6 to PyPI, it includes a fix :) https://mitogen.readthedocs.io/en/latest/changelog.html#v0-2-6-2019-03-06

Thanks a ton for reporting this anyway! And please let me know if it's still broken for you in 0.2.6.

**Comment by opoplawski** [comment]
They are x86_64 hosts, but I'll try with 0.2.6

**Comment by dw** [comment]
In 0.2.6 those fields were forced to be signed 64-bit, so no munging should be required for the thread ID or instance ID (both of which might be negative after IIRC Python applies its hash randomization).

But this hadn't manifested on 64-bit before. Are they Intel machines? It's possible it was pure luck this only turned up on ARM the first time around

**Comment by dw** [comment]
This might be an entirely different issue -- it's not Latch, it's subprocess. Please don't waste time retesting yet, this looks like something different to what I just said :(

**Comment by dw** [comment]
It's the process affinity code

**Comment by dw** [comment]
How many CPUs in the machines that failed?

**Comment by opoplawski** [comment]
80

**Comment by dw** [comment]
Hi Orion,

This is on master. There should be another release within weeks. Apologies for the inconvenience, and please let me know if you have any more issues. Thanks again!

**Comment by opoplawski** [comment]
This patch seems to have done the trick.  Thanks for the extremely fast fix.
