### ISSUE TITLE
ANSIBLE Gathering facts fail on hosts

### ISSUE THREAD

**Issue by yodatak** [dw/mitogen#596]
* Which version of Ansible are you running? 2.8
* Is your version of Ansible patched in any way? no
* Are you running with any custom modules, or `module_utils` loaded? no
* Have you tried the latest master version from Git? yes
* Mention your host and target OS and versions python 2.7  RH7
* Mention your host and target Python versions python 2.7.5 RH7

Whit mitogen master and ansible 2.8 i got on some host this error with gathering_facts: true with mitogen free strategy

`TASK [Gathering Facts] *********************************************************
task path: /appli/projects/pic/jenkins/builds/XXX/workspace/XXX/ansible-XXX/playbooks/_init.yml:108
The full traceback is:
Traceback (most recent call last):
  File "/appli/projects/pic/jenkins/builds/XXX/workspace/XXX/virtualenv_XXX/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 144, in run
    res = self._execute()
  File "/appli/projects/pic/jenkins/builds/XXX/workspace/XXX/virtualenv_XXX/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 648, in _execute
    result = self._handler.run(task_vars=variables)
  File "/appli/projects/pic/jenkins/builds/XXX/workspace/XXX/virtualenv_XXX/lib/python2.7/site-packages/ansible/plugins/action/gather_facts.py", line 66, in run
    res = self._execute_module(module_name=fact_module, module_args=mod_args, task_vars=task_vars, wrap_async=False)
  File "/appli/projects/pic/jenkins/builds/XXX/workspace/XXX/virtualenv_XXX/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 774, in _execute_module
    self._make_tmp_path()
  File "/appli/projects/pic/jenkins/builds/XXX/workspace/XXX/virtualenv_XXX/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 342, in _make_tmp_path
    result = self._low_level_execute_command(cmd, sudoable=False)
  File "/appli/projects/pic/jenkins/builds/XXX/workspace/XXX/virtualenv_XXX/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 1060, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/appli/projects/pic/jenkins/builds/XXX/workspace/XXX/virtualenv_XXX/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 1188, in exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/appli/projects/pic/jenkins/builds/XXX/workspace/XXX/virtualenv_XXX/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 411, in wrapped
    _handle_error(remaining_retries, cmd[0], return_tuple, self._play_context.no_log, self.host)
  File "/appli/projects/pic/jenkins/builds/XXX/workspace/XXX/virtualenv_XXX/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 364, in _handle_error
    display.vvv(msg, host=host)
  File "/appli/projects/pic/jenkins/builds/XXX/workspace/XXX/virtualenv_XXX/lib/python2.7/site-packages/ansible/utils/display.py", line 185, in vvv
    return self.verbose(msg, host=host, caplevel=2)
  File "/appli/projects/pic/jenkins/builds/XXX/workspace/XXX/virtualenv_XXX/lib/python2.7/site-packages/ansible/utils/display.py", line 210, in verbose
    self.display("<%s> %s" % (host, msg), color=C.COLOR_VERBOSE, stderr=to_stderr)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6523: ordinal not in range(128)

fatal: [XXX]: FAILED! => {}

MSG:

Unexpected failure during module execution.`

**Comment by yodatak** [comment]
It was not ansible mitogen from so i close !
