### ISSUE TITLE
AssertionError during connect

### ISSUE THREAD

**Issue by dw** [dw/mitogen#645]
[reported via Reddit]

Hi,

I was running mitogen 0.2.6 and ansible 2.7.

Recently updated to ansible 2.8 and mitogen 0.2.8 provided by EPEL repository on a RHEL7.7 box.

I get the following message at Ansible startup (ad-hoc or playbook):

```
ERROR! [mux  16242] 11:00:45.438541 E mitogen.service: Pool(5bd0, size=32, th='mitogen.Pool.5bd0.7'): while invoking u'get' of u'ansible_mitogen.services.ContextService'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mitogen/service.py", line 621, in _on_service_call
    return invoker.invoke(method_name, kwargs, msg)
  File "/usr/lib/python2.7/site-packages/mitogen/service.py", line 307, in invoke
    response = self._invoke(method_name, kwargs, msg)
  File "/usr/lib/python2.7/site-packages/mitogen/service.py", line 293, in _invoke
    ret = method(**kwargs)
  File "/usr/lib/python2.7/site-packages/ansible_mitogen/services.py", line 467, in get
    reraise(*result)
  File "/usr/lib/python2.7/site-packages/ansible_mitogen/services.py", line 425, in _wait_or_start
    response = self._connect(key, spec, via=via)
  File "/usr/lib/python2.7/site-packages/ansible_mitogen/services.py", line 377, in _connect
    context = method(via=via, unidirectional=True, **spec['kwargs'])
  File "/usr/lib/python2.7/site-packages/mitogen/parent.py", line 2501, in ssh
    return self.connect(u'ssh', **kwargs)
  File "/usr/lib/python2.7/site-packages/mitogen/parent.py", line 2443, in connect
    return self._connect(klass, **mitogen.core.Kwargs(kwargs))
  File "/usr/lib/python2.7/site-packages/mitogen/parent.py", line 2423, in _connect
    conn.connect(context=context)
  File "/usr/lib/python2.7/site-packages/mitogen/parent.py", line 1705, in connect
    raise self.exception
AssertionError
```

**Comment by dw** [comment]
Duplicate of #646
