### ISSUE TITLE
mitogen fails when a malformed ~/.pam_environment file is encountered

### ISSUE THREAD

**Issue by dcarrillo** [dw/mitogen#647]
Hi,

Maybe this is not a (mitogen) bug, but just for your knowledge, by mistake, I had the following `~/.pam_environment` file:
```bash
SSH_AUTH_SOCK DEFAULT="${XDG_RUNTIME_DIR}/ssh-agent.socket
```
Please note the missing closing quotation.

When I run a playbook with mitogen enabled, mitogen (shlex library actually) raises an exception and exits:

```bash
Traceback (most recent call last):
  File "/home/dani/.virtualenvs/server-setup/bin/ansible-playbook", line 110, in <module>
    exit_code = cli.run()
  File "/home/dani/.virtualenvs/server-setup/lib/python3.7/site-packages/ansible/cli/playbook.py", line 123, in run
    results = pbex.run()
  File "/home/dani/.virtualenvs/server-setup/lib/python3.7/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/home/dani/.virtualenvs/server-setup/lib/python3.7/site-packages/ansible/executor/task_queue_manager.py", line 228, in run
    strategy = strategy_loader.get(new_play.strategy, self)
  File "/home/dani/.virtualenvs/server-setup/lib/python3.7/site-packages/ansible/plugins/loader.py", line 558, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/home/dani/.virtualenvs/server-setup/lib/python3.7/site-packages/ansible/plugins/loader.py", line 536, in _load_module_source
    module = imp.load_source(to_native(full_name), to_native(path), module_file)
  File "/home/dani/.virtualenvs/server-setup/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dani/server-setup/mitogen/ansible_mitogen/plugins/strategy/mitogen_linear.py", line 56, in <module>
    import ansible_mitogen.strategy
  File "/home/dani/server-setup/mitogen/ansible_mitogen/strategy.py", line 42, in <module>
    import ansible_mitogen.mixins
  File "/home/dani/server-setup/mitogen/ansible_mitogen/mixins.py", line 53, in <module>
    import ansible_mitogen.connection
  File "/home/dani/server-setup/mitogen/ansible_mitogen/connection.py", line 51, in <module>
    import ansible_mitogen.process
  File "/home/dani/server-setup/mitogen/ansible_mitogen/process.py", line 63, in <module>
    import ansible_mitogen.services
  File "/home/dani/server-setup/mitogen/ansible_mitogen/services.py", line 58, in <module>
    import ansible_mitogen.target
  File "/home/dani/server-setup/mitogen/ansible_mitogen/target.py", line 85, in <module>
    import ansible_mitogen.runner
  File "/home/dani/server-setup/mitogen/ansible_mitogen/runner.py", line 269, in <module>
    _pam_env_watcher = EnvironmentFileWatcher('~/.pam_environment')
  File "/home/dani/server-setup/mitogen/ansible_mitogen/runner.py", line 184, in __init__
    key for key, value in self._load()
  File "/home/dani/server-setup/mitogen/ansible_mitogen/runner.py", line 202, in _load
    return list(self._parse(fp))
  File "/home/dani/server-setup/mitogen/ansible_mitogen/runner.py", line 214, in _parse
    bits = shlex_split_b(line)
  File "/home/dani/server-setup/mitogen/ansible_mitogen/runner.py", line 115, in shlex_split_b
    for t in shlex.split(s.decode('latin1'), comments=True)
  File "/usr/lib64/python3.7/shlex.py", line 305, in split
    return list(lex)
  File "/usr/lib64/python3.7/shlex.py", line 295, in __next__
    token = self.get_token()
  File "/usr/lib64/python3.7/shlex.py", line 105, in get_token
    raw = self.read_token()
  File "/usr/lib64/python3.7/shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
```
I know this is an edge case, I don't even know why were I using ~/.pam_environment but sounds like mitogen could handle this situation better with a warning only.

Thank you.

PS: As an exercise of propaganda:

Running the playbook against a single server:

without mitogen:
`Playbook run took 0 days, 0 hours, 0 minutes, 52 seconds`

with mitogen:
`Playbook run took 0 days, 0 hours, 0 minutes, 25 seconds`

**Comment by ohdearaugustin** [comment]
I had the same issue.

**Comment by MarkusTeufelberger** [comment]
Ran into this issue with the following part in `hosts.ini`:

```
[all:vars]
ansible_python_interpreter=/usr/bin/python3  # force python3 everywhere for now to make sure auto-discovery doesn't interfere
```

This lead to mitogen getting the following `ansible_python_interpeter` string: `/usr/bin/python3  # force python3 everywhere for now to make sure auto-discovery doesn't interfere`

This in turn lead to issues, because there's a single single quite `'` in `doesn't`. The workaround was to put the comment on a different line instead of the same line. The proper fix would probably be stripping comments and whitespace first I guess.
