### ISSUE TITLE
PyVim on Mitogen blacklist with vmware_guest module

### ISSUE THREAD

**Issue by dsgnr** [dw/mitogen#654]
It appeas that `vmware_guest` has a dependency that is in a blacklist within Mitogen. I'm unsure whether this is expected behavour (I've searched the codebase and can't find any references to pyVim). 

Example snippet from my role:
~~~ shell
120 - name: Create VM from template
121   vmware_guest:
122     validate_certs: False
123     hostname: "{{ vcenter_hostname }}"
124     username: "{{ vcenter_user }}"
125     password: "{{ vcenter_pass }}"
126     cluster: "LAB"
127     datacenter: Rack
128     name: "{{ vmname }}"
129     template: "{{ vmtemplate }}"
130     folder: /
131     state: poweredon
132     networks:
133       - name: "{{ vmnetwork }}"
134         start_connected: true
135         ip: "{{ vmipaddr }}"
136         netmask: "{{ vmnetmask }}"
137         gateway: "{{ vmgateway }}"
138         domain: "{{ domain_root }}"
139         dns_servers:
140           - "{{ dns_server_ip }}"
141         type: static
142     customization:
143       dns_servers:
144         - "{{ dns_server_ip }}"
145     hardware:
146       memory_mb: "{{ vmmem }}"
147       num_cpus: "{{ vmcpu }}"
148   register: newvm
~~~

The traceback:
~~~ shell
The full traceback is:
Traceback (most recent call last):
  File "master:/usr/local/lib/python2.7/site-packages/ansible/module_utils/vmware.py", line 32, in <module>
    from pyVim import connect
  File "<stdin>", line 1323, in load_module
  File "<stdin>", line 1254, in _refuse_imports
ImportError: u'pyVim' is present in the Mitogen importer blacklist, therefore this context will not attempt to request it from the master, as the request will always be refused.
~~~

Ansible version:
~~~ shell
➜  ansible ansible --version
ansible 2.8.5
  config file = /Users/dan/.ansible.cfg
  configured module search path = [u'/Users/dan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Jun 19 2019, 07:40:37) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]
~~~

Mitogen version:
~~~ shell
➜  ansible pip show mitogen
 Name: mitogen
Version: 0.2.8
Summary: Library for writing distributed self-replicating programs.
Home-page: https://github.com/dw/mitogen/
Author: David Wilson
Author-email: UNKNOWN
License: New BSD
Location: /usr/local/lib/python2.7/site-packages
Requires:
Required-by:
~~~

Ansible config:
~~~ shell
➜  ansible-config dump --only-changed`
ANSIBLE_PIPELINING(/Users/dan/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/dan/.ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_RETRIES(/Users/dan/.ansible.cfg) = 3
DEFAULT_FILTER_PLUGIN_PATH(/Users/dan/.ansible.cfg) = [u'/etc/ansible/plugins/filter']
DEFAULT_FORKS(/Users/dan/.ansible.cfg) = 30
DEFAULT_GATHERING(/Users/dan/.ansible.cfg) = smart
DEFAULT_INTERNAL_POLL_INTERVAL(/Users/dan/.ansible.cfg) = 0.001
DEFAULT_POLL_INTERVAL(/Users/dan/.ansible.cfg) = 1
DEFAULT_ROLES_PATH(/Users/dan/.ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles', u'/ansible/roles']
DEFAULT_STRATEGY(/Users/dan/.ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/Users/dan/.ansible.cfg) = [u'/Users/dan/.ansible/mitogen/ansible_mitogen/plugins/strategy']
HOST_KEY_CHECKING(/Users/dan/.ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/dan/.ansible.cfg) = False
~~~

Are you able to advise a workaround, or whether this is unexpected at all?

**Comment by faivirol** [comment]
This is still a problem with Mitogen 0.3.3. To work around it, delegate the task to localhost (that way Mitogen doesn't have to transfer the module) with `delegate_to: localhost` on the task or disable Mitogen for that task (requires putting it in a separate play, strategy plugins [can't be specified on the role/task level](https://docs.ansible.com/ansible/latest/plugins/strategy.html#using-strategy-plugins)) like this:

```
- hosts: localhost
  strategy: linear
  tasks:
    - <vmware module>

- hosts: all
  strategy: mitogen_linear # can be omitted if set in ansible.cfg
  <role/task list>
  ```
