### ISSUE TITLE
delegate_to fails with broker already exited

### ISSUE THREAD

**Issue by tmeinlschmidt** [dw/mitogen#663]
Please drag-drop large logs as text file attachments.

Feel free to write an issue in your preferred format, however if in doubt, use
the following checklist as a guide for what to include.

* Which version of Ansible are you running?
2.8.6
* Is your version of Ansible patched in any way?
nope
* Are you running with any custom modules, or `module_utils` loaded?
nope
* Have you tried the latest master version from Git?
nope
* Do you have some idea of what the underlying problem may be?
  https://mitogen.networkgenomics.com/ansible_detailed.html#common-problems has
  instructions to help figure out the likely cause and how to gather relevant
  logs.
* Mention your host and target OS and versions
ubuntu 14.04
* Mention your host and target Python versions
mitogen 2.8, python 3.7.3

the code is simple:
```
---
- name: Enable spark2 as default
  delegate_to: "{{ item }}"
  copy:
    src: spark2.sh
    dest: /etc/profile.d/spark2.sh
    mode: "0644"
  with_items: "{{ hostgroups|get_nodes_with_component(stackgroups, 'ALL_CLIENTS') }}"
```

this ends up with
```
Exception ignored in: <function Connection.__del__ at 0x7f99a9fd8b70>
Traceback (most recent call last):
  File "/home/meinlsch/clusterops/_internal/mitogen-0.2.8/ansible_mitogen/connection.py", line 513, in __del__
    self.close()
  File "/home/meinlsch/clusterops/_internal/mitogen-0.2.8/ansible_mitogen/connection.py", line 816, in close
    self._mitogen_reset(mode='put')
  File "/home/meinlsch/clusterops/_internal/mitogen-0.2.8/ansible_mitogen/connection.py", line 797, in _mitogen_reset
    self.chain.reset()
  File "/home/meinlsch/clusterops/_internal/mitogen-0.2.8/mitogen/parent.py", line 1845, in reset
    self.call_no_reply(mitogen.core.Dispatcher.forget_chain, saved)
  File "/home/meinlsch/clusterops/_internal/mitogen-0.2.8/mitogen/parent.py", line 1900, in call_no_reply
    self.context.send(self.make_msg(fn, *args, **kwargs))
  File "/home/meinlsch/clusterops/_internal/mitogen-0.2.8/mitogen/core.py", line 2267, in send
    self.router.route(msg)
  File "/home/meinlsch/clusterops/_internal/mitogen-0.2.8/mitogen/core.py", line 3344, in route
    self.broker.defer(self._async_route, msg)
  File "/home/meinlsch/clusterops/_internal/mitogen-0.2.8/mitogen/core.py", line 2820, in defer
    raise Error(self.broker_shutdown_msg)
mitogen.core.Error: An attempt was made to enqueue a message with a Broker that has already exitted. It is likely your program called Broker.shutdown() too early.
```

trace:
```
The full traceback is:
Traceback (most recent call last):
  File "/home/meinlsch/clusterops/.condaenv/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 111, in run
    item_results = self._run_loop(items)
  File "/home/meinlsch/clusterops/.condaenv/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 371, in _run_loop
    res = self._execute(variables=task_vars)
  File "/home/meinlsch/clusterops/.condaenv/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 664, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/meinlsch/clusterops/_internal/mitogen-0.2.8/ansible_mitogen/mixins.py", line 116, in run
    return super(ActionModuleMixin, self).run(tmp, task_vars)
  File "/home/meinlsch/clusterops/.condaenv/lib/python3.7/site-packages/ansible/plugins/action/copy.py", line 517, in run
    module_return = self._copy_file(source_full, source_rel, content, content_tempfile, dest, task_vars, follow)
  File "/home/meinlsch/clusterops/.condaenv/lib/python3.7/site-packages/ansible/plugins/action/copy.py", line 378, in _copy_file
    module_return = self._execute_module(module_name='file', module_args=new_module_args, task_vars=task_vars)
  File "/home/meinlsch/clusterops/_internal/mitogen-0.2.8/ansible_mitogen/mixins.py", line 359, in _execute_module
    timeout_secs=self.get_task_timeout_secs(),
  File "/home/meinlsch/clusterops/_internal/mitogen-0.2.8/ansible_mitogen/planner.py", line 493, in invoke
    planner = _get_planner(invocation)
  File "/home/meinlsch/clusterops/_internal/mitogen-0.2.8/ansible_mitogen/planner.py", line 476, in _get_planner
    LOG.debug('%r rejected %r', planner, invocation.module_name)
  File "/home/meinlsch/clusterops/.condaenv/lib/python3.7/logging/__init__.py", line 1371, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/home/meinlsch/clusterops/.condaenv/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/home/meinlsch/clusterops/.condaenv/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/home/meinlsch/clusterops/.condaenv/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/home/meinlsch/clusterops/.condaenv/lib/python3.7/logging/__init__.py", line 907, in handle
    self.release()
  File "/home/meinlsch/clusterops/.condaenv/lib/python3.7/logging/__init__.py", line 861, in release
    self.lock.release()
RuntimeError: cannot release un-acquired lock
```

**Comment by tmeinlschmidt** [comment]
Found this fails with multiple `delegate_to` with `loop` in a row, so as a workaround using `include_tasks` like

```
# host_action.yml
- name: do something
  delegate_to: "{{ delegate_host }}
  ...
```

```
# main.yml
- include_tasks: host_action.yml
  loop: "{{ list_of_hosts }}"
  loop_control:
    looo_var: delegate_host
```

**Comment by adrian-taut-idnow** [comment]
Hello guys, any update on this one? I just hit it

**Comment by sbaudoin** [comment]
Hello, the same for me as well
