### ISSUE TITLE
Missing "pipe buffer full" test on Waker since 0.2.9

### ISSUE THREAD

**Issue by zougloub** [dw/mitogen#667]
Hi,

Here's a tiny piece of code where I tried to implement something that would retrieve a stream of lines of text, I would have expected to be working, but is not when there are many lines:

```py
#!/usr/bin/env python
# -*- coding:utf-8 vi:noet
# mitogen test

import mitogen.master, mitogen.utils, mitogen.select

def count(n, sender):
	for i in range(n):
		sender.send("{}".format(i))
	sender.close()

if __name__ == "__main__":
	mitogen.utils.log_to_file(
	 #io=True,
	 #level="DEBUG",
	)
	broker = mitogen.master.Broker()
	router = mitogen.master.Router(broker)
	#router.enable_debug()

	remote = router.local(
	 #debug=True,
	)

	recv = mitogen.core.Receiver(router)
	x = remote.call_async(count, 100000, recv.to_sender())
	sel = mitogen.select.Select([recv, x], oneshot=False)
	while True: # test!
		ev = sel.get_event()
		msg = ev.data
		if ev.source is recv:
			print(msg.unpickle())
```

The loop is halting at random counts, with something like:
```
1920
1921
1922
1923
Traceback (most recent call last):
  File "test-mitogen-recv.py", line 29, in <module>
    ev = sel.get_event()
  File ".../mitogen/select.py", line 335, in get_event
    event.data = recv.get(block=False)
  File ".../mitogen/core.py", line 1181, in get
    msg._throw_dead()
  File ".../mitogen/core.py", line 921, in _throw_dead
    raise ChannelError(self.data.decode('utf-8', 'replace'))
mitogen.core.ChannelError: the respondent Context has disconnected
```

and I'm not sure what to make of it.

As I'm not experienced with mitogen I'm probably missing something... but I barely tried to implement the `deliver_monthly_report` example from `to_sender()` doc.

Thanks,

**Comment by dw** [comment]
With debug logging enabled,

```
14:13:04.802550 D mitogen.[local.6864]: Broker(5fd0): shutting down
14:13:04.802636 I stderr.[local.6864]: Traceback (most recent call last):
14:13:04.802700 I stderr.[local.6864]:   File "<stdin>", line 3999, in <module>
14:13:04.802758 I stderr.[local.6864]:   File "<stdin>", line 3997, in main
14:13:04.802813 I stderr.[local.6864]:   File "<stdin>", line 3577, in shutdown
14:13:04.802868 I stderr.[local.6864]:   File "/usr/lib/python2.7/logging/__init__.py", line 1162, in debug
14:13:04.802922 I stderr.[local.6864]:     self._log(DEBUG, msg, args, **kwargs)
14:13:04.802976 I stderr.[local.6864]:   File "/usr/lib/python2.7/logging/__init__.py", line 1293, in _log
14:13:04.803030 I stderr.[local.6864]:     self.handle(record)
14:13:04.803083 I stderr.[local.6864]:   File "/usr/lib/python2.7/logging/__init__.py", line 1303, in handle
14:13:04.803135 I stderr.[local.6864]:     self.callHandlers(record)
14:13:04.803187 I stderr.[local.6864]:   File "/usr/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
14:13:04.803240 I stderr.[local.6864]:     hdlr.handle(record)
14:13:04.803292 I stderr.[local.6864]:   File "/usr/lib/python2.7/logging/__init__.py", line 766, in handle
14:13:04.803344 I stderr.[local.6864]:     self.emit(record)
14:13:04.803396 I stderr.[local.6864]:   File "<stdin>", line 1606, in emit
14:13:04.803447 I stderr.[local.6864]:   File "<stdin>", line 2272, in send
14:13:04.803498 I stderr.[local.6864]:   File "<stdin>", line 3345, in route
14:13:04.803550 I stderr.[local.6864]:   File "<stdin>", line 2831, in defer
14:13:04.803601 I stderr.[local.6864]:   File "<stdin>", line 2801, in _wake
14:13:04.803652 I stderr.[local.6864]:   File "<stdin>", line 2033, in write
14:13:04.803703 I stderr.[local.6864]:   File "<stdin>", line 553, in io_op
14:13:04.803755 I stderr.[local.6864]: OSError: [Errno 11] Resource temporarily unavailable
```

This is new in mitogen 0.2.9, 0.2.8 works fine. 0.2.9 modified how other threads wake the broker thread to remove some synchronization around an internal pipe. The error is because the pipe buffer is full, it seems the broker never had any chance to run after 4096 wakes by the main thread.

Please install 0.2.8 for now. 

Fix is either restore the old synchronization (expensive) or simply masking the error in _wake()

**Comment by zougloub** [comment]
Thanks @dw for the prompt response!

**Comment by dw** [comment]
Whoops :)

```diff
diff --git a/mitogen/core.py b/mitogen/core.py
index d8c57ba7..4dd44925 100644
--- a/mitogen/core.py
+++ b/mitogen/core.py
@@ -2801,7 +2801,7 @@ class Waker(Protocol):
             self.stream.transmit_side.write(b(' '))
         except OSError:
             e = sys.exc_info()[1]
-            if e.args[0] in (errno.EBADF, errno.EWOULDBLOCK):
+            if e.args[0] not in (errno.EBADF, errno.EWOULDBLOCK):
                 raise
 
```

This is fixed on `dmw` branch, will be on master sometime later today.

**Comment by dw** [comment]
This is now on the master branch and will make it into the next release. To be updated when a new release is made, subscribe to https://networkgenomics.com/mail/mitogen-announce/

Thanks for reporting this!
