### ISSUE TITLE
mitogen crashed when running delegate action with iptable task and python3

### ISSUE THREAD

**Issue by Ehekatl** [dw/mitogen#677]
* Which version of Ansible are you running?
ansible 2.5.0
* Is your version of Ansible patched in any way?
no
* Are you running with any custom modules, or `module_utils` loaded?
no

* Have you tried the latest master version from Git?
no, didn't find anything related in changelog

* Do you have some idea of what the underlying problem may be?

  Python2 works fine
  reproducible run ansible with ansible_python_interpreter=/usr/bin/python3 cause the problem

* Mention your host and target OS and versions
  Ubuntu 18.04
  
* Mention your host and target Python versions
  Python 3.4.0 on delegate host
  Python 3.6.8 on remote host

Example task to trigger this problem:

```
# sudo iptables -I INPUT 1 -p $PROTO -s $HOST --dport $PORT -j ACCEPT
- iptables:
    action: insert
    chain: INPUT
    rule_num: 1
    destination_port: 8500
#      to_ports: 8500
    source: "{{inventory_hostname}}"
    protocol: tcp
    #policy: ACCEPT
    jump: ACCEPT
  delegate_to: 2.2.2.2
  become: yes
  tags: iptables
  ignore_errors: True
``` 

```
ERROR! [mux  13358] 08:38:34.982518 E mitogen.[ssh.2.2.2.2:22]: ExternalContext.main() crashed
Traceback (most recent call last):
  File "<stdin>", line 3981, in main
  File "<stdin>", line 3718, in run
  File "<stdin>", line 633, in _profile_hook
  File "<stdin>", line 3707, in _dispatch_calls
  File "<stdin>", line 3653, in _dispatch_one
  File "<stdin>", line 3640, in _parse_request
  File "<stdin>", line 668, in import_module
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "<stdin>", line 1508, in load_module
  File "master:/home/devops/ansible_tools/third_party/mitogen-0.2.8/ansible_mitogen/target.py", line 85, in <module>
    import ansible_mitogen.runner
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "<stdin>", line 1508, in load_module
  File "master:/home/devops/ansible_tools/third_party/mitogen-0.2.8/ansible_mitogen/runner.py", line 85, in <module>
    import ansible.module_utils.basic
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "<stdin>", line 1508, in load_module
  File "master:/usr/local/lib/python3.6/site-packages/ansible/module_utils/basic.py", line 262, in <module>
    sys.exit(1)
SystemExit: 1
fatal: [1.1.1.1]: UNREACHABLE! => {"changed": false, "msg": "Channel was disconnected while connection attempt was in progress; this may be caused by an abnormal Ansible exit, or due to an unreliable target.", "unreachable": true}
```

**Comment by perfectayush** [comment]
Facing same issue with delegate_to in `at` module with similar error stacktrace. 
I have observed that issue is with python 3.4.3 on delegated host. 
Overriding `ansible_python_interpreter` to python 2.7.6, is fixing the issue.

This is reflecting when running simple `ping`  command as well:
I think the mitogen for ansible documentation here: https://mitogen.networkgenomics.com/changelog.html states that it supports python versions:  Python 2.6, 2.7 or 3.6, so that's the issue.
Using latest mitogen from git master commit a18be5afefd1c8b7a860a994773737f788405a93 to get the python interpreter discovery.
```
❯ ansible2 <server> -m ping  -e ansible_python_interpreter="/usr/bin/python2"
xx.x.x.xxx | SUCCESS => {
    "changed": false,
    "ping": "pong"
}


❯ ansible2 <server> -m ping  -e ansible_python_interpreter="/usr/bin/python3"
ERROR! [mux  11062] 07:24:17.833473 E mitogen.[ssh.xx.x.x.xxx]: ExternalContext.main() crashed
Traceback (most recent call last):
  File "<stdin>", line 3989, in main
  File "<stdin>", line 3726, in run
  File "<stdin>", line 633, in _profile_hook
  File "<stdin>", line 3715, in _dispatch_calls
  File "<stdin>", line 3661, in _dispatch_one
  File "<stdin>", line 3648, in _parse_request
  File "<stdin>", line 668, in import_module
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "<stdin>", line 1508, in load_module
  File "master:/opt/ansible2/lib/python3.5/site-packages/ansible_mitogen/target.py", line 85, in <module>
    import ansible_mitogen.runner
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "<stdin>", line 1508, in load_module
  File "master:/opt/ansible2/lib/python3.5/site-packages/ansible_mitogen/runner.py", line 85, in <module>
    import ansible.module_utils.basic
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "<stdin>", line 1508, in load_module
  File "master:/opt/ansible2/lib/python3.5/site-packages/ansible/module_utils/basic.py", line 276, in <module>
    sys.exit(1)
SystemExit: 1
xx.x.x.xxx | UNREACHABLE! => {
    "changed": false,
    "msg": "Channel was disconnected while connection attempt was in progress; this may be caused by an abnormal Ansible exit, or due to an unreliable target.",
    "unreachable": true
}
```
