### ISSUE TITLE
ascii' codec can't encode characters in position 109-117: ordinal not in range(128)

### ISSUE THREAD

**Issue by changchichung** [dw/mitogen#713]
* Which version of Ansible are you running?

ansible 2.9.7

* Is your version of Ansible patched in any way?

 NO

* Are you running with any custom modules, or `module_utils` loaded?

No

* Have you tried the latest master version from Git?

No

* Do you have some idea of what the underlying problem may be?

No

* Mention your host and target OS and versions

ubuntu 14.04 server 

* Mention your host and target Python versions

python 2.7.6 and python 3.6

* If reporting a crash or hang in Ansible, please rerun with -vvv and include
  200 lines of output around the point of the error, along with a full copy of
  any traceback or error text in the log. Beware "-vvv" may include secret
  data! Edit as necessary before posting.

```
The full traceback is:
Traceback (most recent call last):
  File "/home/admin/ansible_newversion/.ve/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/home/admin/ansible_newversion/.ve/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/admin/ansible_newversion/mitogen-0.2.9/ansible_mitogen/mixins.py", line 121, in run
    return super(ActionModuleMixin, self).run(tmp, task_vars)
  File "/home/admin/ansible_newversion/.ve/local/lib/python2.7/site-packages/ansible/plugins/action/gather_facts.py", line 79, in run
    res = self._execute_module(module_name=fact_module, module_args=mod_args, task_vars=task_vars, wrap_async=False)
  File "/home/admin/ansible_newversion/mitogen-0.2.9/ansible_mitogen/mixins.py", line 351, in _execute_module
    self._set_temp_file_args(module_args, wrap_async)
  File "/home/admin/ansible_newversion/mitogen-0.2.9/ansible_mitogen/mixins.py", line 330, in _set_temp_file_args
    self._connection.get_good_temp_dir()
  File "/home/admin/ansible_newversion/mitogen-0.2.9/ansible_mitogen/connection.py", line 775, in get_good_temp_dir
    self._connect()
  File "/home/admin/ansible_newversion/mitogen-0.2.9/ansible_mitogen/connection.py", line 797, in _connect
    self._connect_stack(stack)
  File "/home/admin/ansible_newversion/mitogen-0.2.9/ansible_mitogen/connection.py", line 748, in _connect_stack
    stack=mitogen.utils.cast(list(stack)),
  File "/home/admin/ansible_newversion/mitogen-0.2.9/mitogen/service.py", line 120, in call
    return call_context.call_service(service_name, method_name, **kwargs)
  File "/home/admin/ansible_newversion/mitogen-0.2.9/mitogen/core.py", line 2276, in call_service
    return recv.get().unpickle()
  File "/home/admin/ansible_newversion/mitogen-0.2.9/mitogen/core.py", line 963, in unpickle
    raise obj
CallError: exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 109-117: ordinal not in range(128)
  File "/home/admin/ansible_newversion/mitogen-0.2.9/mitogen/service.py", line 621, in _on_service_call
    return invoker.invoke(method_name, kwargs, msg)
  File "/home/admin/ansible_newversion/mitogen-0.2.9/mitogen/service.py", line 307, in invoke
    response = self._invoke(method_name, kwargs, msg)
  File "/home/admin/ansible_newversion/mitogen-0.2.9/mitogen/service.py", line 293, in _invoke
    ret = method(**kwargs)
  File "/home/admin/ansible_newversion/mitogen-0.2.9/ansible_mitogen/services.py", line 503, in get
    'msg': str(e),

fatal: [hqpc074.abc.com]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}

```

* If reporting any kind of problem with Ansible, please include the Ansible
  version along with output of "ansible-config dump --only-changed".

```
ansible-config dump --only-changed
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
DEFAULT_GATHER_TIMEOUT(/home/admin/ansible_newversion/ansible.cfg) = 20
DEFAULT_ROLES_PATH(/home/admin/ansible_newversion/ansible.cfg) = [u'/home/admin/ansible_newversion/roles']
DEFAULT_STRATEGY(/home/admin/ansible_newversion/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/home/admin/ansible_newversion/ansible.cfg) = [u'/home/admin/ansible_newversion/mitogen-0
DEFAULT_TIMEOUT(/home/admin/ansible_newversion/ansible.cfg) = 60
HOST_KEY_CHECKING(/home/admin/ansible_newversion/ansible.cfg) = False

```

any suggestions ?

**Comment by s1113950** [comment]
Can you post a minimally-reproducible playbook here that has this problem?
