### ISSUE TITLE
ModuleNotFoundError: 'nomad' is present in the Mitogen importer blacklist, therefore this context will not attempt to request it from the master, as the request will always be refused.

### ISSUE THREAD

**Issue by atomlab** [dw/mitogen#735]
* ansible==2.9.0
* mitogen==0.2.9
* Python 3.7.3

I'm writing a custom ansible module with [python-nomad](https://github.com/jrxfive/python-nomad) and see strange error. 

```
The error was: ModuleNotFoundError: 'nomad' is present in the Mitogen importer blacklist, therefore this context will not attempt to request it from the master, as the request will always be refused.
```

full error

```
TASK [test] ***************************************************************************************************************************************************************************************
The full traceback is:
Traceback (most recent call last):
  File "master:/Users/user/.virtenv/test/lib/python3.7/site-packages/ansible_mitogen/runner.py", line 975, in _run
    self._run_code(code, mod)
  File "master:/Users/user/.virtenv/test/lib/python3.7/site-packages/ansible_mitogen/runner.py", line 939, in _run_code
    exec(code, vars(mod))
  File "master:/Users/user/DATA/git/test-nodes/ansible/collections/ansible_collections/test/nomad/plugins/modules/nomad_deploy.py", line 8, in <module>
  File "<stdin>", line 1475, in load_module
  File "<stdin>", line 1404, in _refuse_imports
ModuleNotFoundError: 'nomad' is present in the Mitogen importer blacklist, therefore this context will not attempt to request it from the master, as the request will always be refused.
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"master:/Users/user/.virtenv/test/lib/python3.7/site-packages/ansible_mitogen/runner.py\", line 975, in _run\n    self._run_code(code, mod)\n  File \"master:/Users/user/.virtenv/test/lib/python3.7/site-packages/ansible_mitogen/runner.py\", line 939, in _run_code\n    exec(code, vars(mod))\n  File \"master:/Users/user/DATA/git/test-nodes/ansible/collections/ansible_collections/test/nomad/plugins/modules/nomad_deploy.py\", line 8, in <module>\n  File \"<stdin>\", line 1475, in load_module\n  File \"<stdin>\", line 1404, in _refuse_imports\nModuleNotFoundError: 'nomad' is present in the Mitogen importer blacklist, therefore this context will not attempt to request it from the master, as the request will always be refused.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

Code of module

```
#!/usr/bin/python3

from __future__ import absolute_import, division, print_function
__metaclass__ = type

from ansible.module_utils.basic import AnsibleModule

import nomad

def deployment(module, results):
    print("run deployment")


def main():
    module = AnsibleModule(
        argument_spec=dict(
            push=dict(type='bool', default=False),
        )
    )
    results = dict(
        changed=False
    )
    deployment(module, results)
    module.exit_json(**results)

if __name__ == '__main__':
    main()
```

**Comment by s1113950** [comment]
How is `nomad` installed? Is it in your venv here `/Users/user/.virtenv`? That error means that whatever Python Mitogen is using on the host doesn't have the library in question so it prevents a context (target host) from requesting it from the master (where you're running Ansible from) because the lib doesn't exist in the master's Python env.

**Comment by atomlab** [comment]
> How is `nomad` installed? Is it in your venv here `/Users/user/.virtenv`? That error means that whatever Python Mitogen is using on the host doesn't have the library in question so it prevents a context (target host) from requesting it from the master (where you're running Ansible from) because the lib doesn't exist in the master's Python env.

You're right! I have installed `nomad-deploy` only on master host, but not on the remote host.
```
master $ pip3 install nomad-deploy
Collecting nomad-deploy
  Downloading nomad_deploy-1.0.1-py3-none-any.whl (5.1 kB)
Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: jinja2 in /Users/user/.virtenv/test/lib/python3.7/site-packages (from nomad-deploy) (2.10.1)
Requirement already satisfied: pyyaml in /Users/user/.virtenv/test/lib/python3.7/site-packages (from nomad-deploy) (5.1.2)
Collecting python-nomad
  Downloading python_nomad-1.2.1-py3-none-any.whl (28 kB)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/user/.virtenv/test/lib/python3.7/site-packages (from jinja2->nomad-deploy) (1.1.1)
Requirement already satisfied: requests in /Users/user/.virtenv/test/lib/python3.7/site-packages (from python-nomad->nomad-deploy) (2.22.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/user/.virtenv/test/lib/python3.7/site-packages (from requests->python-nomad->nomad-deploy) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/user/.virtenv/test/lib/python3.7/site-packages (from requests->python-nomad->nomad-deploy) (1.25.6)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/user/.virtenv/test/lib/python3.7/site-packages (from requests->python-nomad->nomad-deploy) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /Users/user/.virtenv/test/lib/python3.7/site-packages (from requests->python-nomad->nomad-deploy) (2019.9.11)
Installing collected packages: argparse, python-nomad, nomad-deploy
Successfully installed argparse-1.4.0 nomad-deploy-1.0.1 python-nomad-1.2.1
master$
master$ ansible-playbook playbook_test.yml
```

When I have `nomad-deploy` installed on remote host, the mitogen is working fine!
```
remote$ pip3 install nomad-deploy
Collecting nomad-deploy
  Using cached nomad_deploy-1.0.1-py3-none-any.whl (5.1 kB)
Requirement already satisfied: argparse in /usr/local/lib/python3.8/dist-packages (from nomad-deploy) (1.4.0)
Requirement already satisfied: jinja2 in /usr/lib/python3/dist-packages (from nomad-deploy) (2.10.1)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from nomad-deploy) (5.3.1)
Requirement already satisfied: python-nomad in /usr/local/lib/python3.8/dist-packages (from nomad-deploy) (1.2.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from python-nomad->nomad-deploy) (2.22.0)
Installing collected packages: nomad-deploy
Successfully installed nomad-deploy-1.0.1
```

Thanks for you response!
