### ISSUE TITLE
Ansible 2.10.5 RHEL 8 with package module

### ISSUE THREAD

**Issue by dsgnr** [dw/mitogen#776]
When using the `package` module with the latest RC (as well as latest commit on master branch) of Mitogen for Ansible 2.10.5, I am receiving an exception;
~~~
fatal: [EL8]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"master:/Users/dsgnr/.virtualenvs/ansible/lib/python3.7/site-packages/ansible_mitogen/runner.py\", line 975, in _run\n    self._run_code(code, mod)\n  File \"master:/Users/dsgnr/.virtualenvs/ansible/lib/python3.7/site-packages/ansible_mitogen/runner.py\", line 939, in _run_code\n    exec(code, vars(mod))\n  File \"master:/Users/dsgnr/.virtualenvs/py3/lib/python3.7/site-packages/ansible/modules/dnf.py\", line 1330, in <module>\n  File \"master:/Users/dsgnr/.virtualenvs/py3/lib/python3.7/site-packages/ansible/modules/dnf.py\", line 1319, in main\n  File \"master:/Users/dsgnr/.virtualenvs/py3/lib/python3.7/site-packages/ansible/modules/dnf.py\", line 1288, in run\n  File \"master:/Users/dsgnr/.virtualenvs/py3/lib/python3.7/site-packages/ansible/modules/dnf.py\", line 620, in _base\n  File \"/usr/lib/python3.6/site-packages/dnf/base.py\", line 300, in init_plugins\n    self._plugins._load(self.conf, disabled_glob, enable_plugins)\n  File \"/usr/lib/python3.6/site-packages/dnf/plugin.py\", line 131, in _load\n    raise RuntimeError(\"load_plugins() called twice\")\nRuntimeError: load_plugins() called twice\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
~~~
~~~
+- name: Install package
+  package:
+    name: "{{ package }}"
+    state: present
~~~

However, using the individual modules works fine;

~~~
+- name: Install package for Ubuntu
+  apt:
+    name: "{{ package }}"
+    state: present
+  when: ansible_os_family == "Ubuntu"
+
+- name: Install package for RHEL up to version 7
+  yum:
+    name: "{{ package }}"
+    state: present
+  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 7
+
+- name: Install package for RHEL 8
+  dnf:
+    name: "{{ package }}"
+    state: present
+  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 8
~~~

* Which version of Ansible are you running?
Ansible 2.10.5

* Is your version of Ansible patched in any way?
* No

* Are you running with any custom modules, or `module_utils` loaded?
No
* Have you tried the latest master version from Git?
Running v0.3.0-rc.0

* Do you have some idea of what the underlying problem may be?

* Mention your host and target OS and versions
Red Hat Enterprise Linux release 8.3 (Ootpa)

* Mention your host and target Python versions
~~~
# /usr/libexec/platform-python
Python 3.6.8 (default, Aug 18 2020, 08:33:21)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
~~~

**Comment by wouterhummelink** [comment]
This also occurs if the dnf/yum module is used more than once in the same playbook.
```yaml
ansible_facts: {}
  module_stderr: |-
    Traceback (most recent call last):
      File "master:/home/wouterhummelink/.local/lib/python3.9/site-packages/ansible_mitogen/runner.py", line 975, in _run
        self._run_code(code, mod)
      File "master:/home/wouterhummelink/.local/lib/python3.9/site-packages/ansible_mitogen/runner.py", line 939, in _run_code
        exec(code, vars(mod))
      File "master:/home/wouterhummelink/.local/lib/python3.9/site-packages/ansible/modules/dnf.py", line 1330, in <module>
      File "master:/home/wouterhummelink/.local/lib/python3.9/site-packages/ansible/modules/dnf.py", line 1319, in main
      File "master:/home/wouterhummelink/.local/lib/python3.9/site-packages/ansible/modules/dnf.py", line 1288, in run
      File "master:/home/wouterhummelink/.local/lib/python3.9/site-packages/ansible/modules/dnf.py", line 620, in _base
      File "/usr/lib/python3.6/site-packages/dnf/base.py", line 300, in init_plugins
        self._plugins._load(self.conf, disabled_glob, enable_plugins)
      File "/usr/lib/python3.6/site-packages/dnf/plugin.py", line 131, in _load
        raise RuntimeError("load_plugins() called twice")
    RuntimeError: load_plugins() called twice
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**Comment by wouterhummelink** [comment]
This could be solved by calling into `dnf.plugin.Plugins._unload()` but I'm not quite sure where such cleanup should go... ansible or mitogen

**Comment by wouterhummelink** [comment]
I've locally patched dnf.py in ansible to call _unload() just before the call to `init_plugins()` that appears to successfully work around this issue.

**Comment by wouterhummelink** [comment]
@moreati The ansible project appears to be unwilling to fix this on their end.

**Comment by moreati** [comment]
thank you, I don't think this will make it into the next release candidate. Possibly the one after.

**Comment by fauust** [comment]
Hi, I can confirm this on 3 centos8 and a rhel8.
Any help you might need in debugging this, just ping me (I am very happy that mitogen finally is usable with ansible 2.10)!

**Comment by Aethylred** [comment]
Another confirmation for CentOS8

**Comment by Madic-** [comment]
As workaround I added the following to the task:

```
  vars:
    mitogen_task_isolation: fork
```

Example:

```
- name: Podman | Installing podman....
  package:
    name:
      - podman
    state: present
  vars:
    mitogen_task_isolation: fork
```

**Comment by fauust** [comment]
@Madic- workaround works for me too.

**Comment by JiffsMaverick** [comment]
I can confirm this bug for Oracle Linux 8. Mitogen 0.3.0-rc1 and ansible-base 2.10.5.

**Comment by moreati** [comment]
#816 attempting to reproduce as part of #816

**Comment by moreati** [comment]
I've reproduced this in https://github.com/moreati/mitogen/tree/issue776

**Comment by annttu** [comment]
Adding `ansible.legacy.dnf` to `ALWAYS_FORK_MODULES` list in ansible_mitogen/planner.py seems to fix this issue with yum.

```--- ./ansible_mitogen/planner.py.orig	2021-03-26 14:19:12.000000000 +0200
+++ ./ansible_mitogen/planner.py	2021-03-26 14:18:56.000000000 +0200
@@ -321,6 +321,7 @@
     ALWAYS_FORK_MODULES = frozenset([
         'dnf',  # issue #280; py-dnf/hawkey need therapy
         'firewalld',  # issue #570: ansible module_utils caches dbus conn
+        'ansible.legacy.dnf',  # issue #776
     ])

     def should_fork(self):
```

**Comment by pun-ky** [comment]
@annttu yep, I could confirm that it works with RHEL8/Python3 and Ansible 2.10 ;

thanks for sharing this fix! guys could you somehow release the fix even as an unofficial version?:)

right now I need to reference fork in my build but it just would be nice to reference your awesome project ;)

**Comment by DaVince** [comment]
> Adding `ansible.legacy.dnf` to `ALWAYS_FORK_MODULES` list in ansible_mitogen/planner.py seems to fix this issue with yum.
> 
> ```
> +++ ./ansible_mitogen/planner.py	2021-03-26 14:18:56.000000000 +0200
> @@ -321,6 +321,7 @@
>      ALWAYS_FORK_MODULES = frozenset([
>          'dnf',  # issue #280; py-dnf/hawkey need therapy
>          'firewalld',  # issue #570: ansible module_utils caches dbus conn
> +        'ansible.legacy.dnf',  # issue #776
>      ])
> 
>      def should_fork(self):
> ```

Can confirm this fixes it on Ansible 2.10.7 on MacOS as well, for both `package` and `dnf`.

**Comment by bradh352** [comment]
If you want to easily install the PR #845 that contains this fix without manually patching, you can run something like:
`pip install git+https://github.com/mitogen-hq/mitogen.git@refs/pull/845/merge`

**Comment by Nothing4You** [comment]
if you look at the `ALWAYS_FORK_MODULES` list you can see that dnf already was in there for a different reason (#280), it just wasn't migrated to the new naming scheme i guess?
