### ISSUE TITLE
import mitogen raises SyntaxError on Python 2.4.x

### ISSUE THREAD

**Issue by moreati** [dw/mitogen#92]
```
~/src/mitogen % python -V     
Python 2.4.4
~/src/mitogen % python -c "import mitogen; mitogen.main()"
Traceback (most recent call last):
  File "<string>", line 1, in ?
  File "mitogen/__init__.py", line 113
    from . import utils
         ^
SyntaxError: invalid syntax
```
Patch in progress

**Comment by moreati** [comment]
There are 2 other modules that use the same syntax in the test suite. I think it will be better to quarantine those tests if and when we are testing on Python 2.4.x.
